coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  backend:
    paths:
      - "!web/"
  frontend:
    paths:
      - "web/"

comment:
  layout: "reach, diff, flags, files"
  require_changes: false
