// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package store

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (fund_id, kind, name, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, fund_id, kind, name, created_at, inactive_on
`

type CreateAccountParams struct {
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.FundID,
		arg.Kind,
		arg.Name,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.InactiveOn,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account
WHERE id = ?
`

// DeleteAccount leans on the composite foreign keys from "transaction" and
// reconciliation_line to refuse it once real data references the account -
// for a never-used duplicate only; a used-then-retired account gets
// UpdateAccount's inactive_on instead.
func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccountForFund = `-- name: GetAccountForFund :one
SELECT id, fund_id, kind, name, created_at, inactive_on
FROM account
WHERE id = ? AND fund_id = ?
`

type GetAccountForFundParams struct {
	ID     int64
	FundID int64
}

// GetAccountForFund is the only single-account lookup, fund-scoped for the
// reason GetMemberForFund is (#188): an account id belonging to another fund
// answers sql.ErrNoRows rather than being found and only then rejected.
func (q *Queries) GetAccountForFund(ctx context.Context, arg GetAccountForFundParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountForFund, arg.ID, arg.FundID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.InactiveOn,
	)
	return i, err
}

const listAccountsByFund = `-- name: ListAccountsByFund :many
SELECT id, fund_id, kind, name, created_at, inactive_on
FROM account
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListAccountsByFund(ctx context.Context, fundID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Kind,
			&i.Name,
			&i.CreatedAt,
			&i.InactiveOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account
SET name        = COALESCE(?1, name),
    kind        = COALESCE(?2, kind),
    inactive_on = CASE WHEN CAST(?3 AS INTEGER) = 1 THEN ?4 ELSE inactive_on END
WHERE id = ?5
RETURNING id, fund_id, kind, name, created_at, inactive_on
`

type UpdateAccountParams struct {
	Name          *string
	Kind          *string
	SetInactiveOn int64
	InactiveOn    *string
	ID            int64
}

// UpdateAccount is a correction to a location's own labels, not a ledger
// event: renaming, re-kinding or retiring an account changes nothing already
// posted (name and kind are both labels, not posted facts - nothing in
// internal/ledger branches on kind, and the schema's CHECK is the only rule
// it carries). name is NOT NULL, so
// COALESCE covers it the same way UpdateMember's does; inactive_on needs the
// set_inactive_on flag for the same reason UpdateMember's does - a null
// argument is ambiguous between "leave alone" and "reinstate".
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.Kind,
		arg.SetInactiveOn,
		arg.InactiveOn,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
		&i.InactiveOn,
	)
	return i, err
}
