// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package store

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (fund_id, kind, name, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, fund_id, kind, name, created_at
`

type CreateAccountParams struct {
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.FundID,
		arg.Kind,
		arg.Name,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, fund_id, kind, name, created_at
FROM account
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByFund = `-- name: ListAccountsByFund :many
SELECT id, fund_id, kind, name, created_at
FROM account
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListAccountsByFund(ctx context.Context, fundID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Kind,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
