// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dues_tier.sql

package store

import (
	"context"
)

const createDuesTier = `-- name: CreateDuesTier :one
INSERT INTO dues_tier (fund_id, name, created_at)
VALUES (?, ?, ?)
RETURNING id, fund_id, name, created_at
`

type CreateDuesTierParams struct {
	FundID    int64
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateDuesTier(ctx context.Context, arg CreateDuesTierParams) (DuesTier, error) {
	row := q.db.QueryRowContext(ctx, createDuesTier, arg.FundID, arg.Name, arg.CreatedAt)
	var i DuesTier
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDuesTier = `-- name: GetDuesTier :one
SELECT id, fund_id, name, created_at
FROM dues_tier
WHERE id = ?
`

func (q *Queries) GetDuesTier(ctx context.Context, id int64) (DuesTier, error) {
	row := q.db.QueryRowContext(ctx, getDuesTier, id)
	var i DuesTier
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listDuesTiersByFund = `-- name: ListDuesTiersByFund :many
SELECT id, fund_id, name, created_at
FROM dues_tier
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListDuesTiersByFund(ctx context.Context, fundID int64) ([]DuesTier, error) {
	rows, err := q.db.QueryContext(ctx, listDuesTiersByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuesTier{}
	for rows.Next() {
		var i DuesTier
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
