// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dues_rate.sql

package store

import (
	"context"
)

const createDuesRate = `-- name: CreateDuesRate :one
INSERT INTO dues_rate (tier_id, amount, effective_from, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, tier_id, amount, effective_from, created_at
`

type CreateDuesRateParams struct {
	TierID        int64
	Amount        int64
	EffectiveFrom string
	CreatedAt     int64
}

func (q *Queries) CreateDuesRate(ctx context.Context, arg CreateDuesRateParams) (DuesRate, error) {
	row := q.db.QueryRowContext(ctx, createDuesRate,
		arg.TierID,
		arg.Amount,
		arg.EffectiveFrom,
		arg.CreatedAt,
	)
	var i DuesRate
	err := row.Scan(
		&i.ID,
		&i.TierID,
		&i.Amount,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const getEffectiveDuesRate = `-- name: GetEffectiveDuesRate :one
SELECT id, tier_id, amount, effective_from, created_at
FROM dues_rate
WHERE tier_id = ? AND effective_from <= ?
ORDER BY effective_from DESC
LIMIT 1
`

type GetEffectiveDuesRateParams struct {
	TierID        int64
	EffectiveFrom string
}

// The rate in force for a period: the latest row whose effective_from is at or
// before it. One-sided intervals mean there is no end date to check, and no
// row at all is a legitimate answer: a tier whose rate is not yet decided.
// effective_from is 'YYYY-MM', so a string comparison is a chronological one.
func (q *Queries) GetEffectiveDuesRate(ctx context.Context, arg GetEffectiveDuesRateParams) (DuesRate, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveDuesRate, arg.TierID, arg.EffectiveFrom)
	var i DuesRate
	err := row.Scan(
		&i.ID,
		&i.TierID,
		&i.Amount,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const listDuesRatesByTier = `-- name: ListDuesRatesByTier :many
SELECT id, tier_id, amount, effective_from, created_at
FROM dues_rate
WHERE tier_id = ?
ORDER BY effective_from
`

func (q *Queries) ListDuesRatesByTier(ctx context.Context, tierID int64) ([]DuesRate, error) {
	rows, err := q.db.QueryContext(ctx, listDuesRatesByTier, tierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuesRate{}
	for rows.Next() {
		var i DuesRate
		if err := rows.Scan(
			&i.ID,
			&i.TierID,
			&i.Amount,
			&i.EffectiveFrom,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
