// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fund.sql

package store

import (
	"context"
)

const createFund = `-- name: CreateFund :one
INSERT INTO fund (name, currency, report_slug, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, currency, report_slug, created_at
`

type CreateFundParams struct {
	Name       string
	Currency   string
	ReportSlug string
	CreatedAt  int64
}

func (q *Queries) CreateFund(ctx context.Context, arg CreateFundParams) (Fund, error) {
	row := q.db.QueryRowContext(ctx, createFund,
		arg.Name,
		arg.Currency,
		arg.ReportSlug,
		arg.CreatedAt,
	)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.ReportSlug,
		&i.CreatedAt,
	)
	return i, err
}

const getFund = `-- name: GetFund :one
SELECT id, name, currency, report_slug, created_at
FROM fund
WHERE id = ?
`

func (q *Queries) GetFund(ctx context.Context, id int64) (Fund, error) {
	row := q.db.QueryRowContext(ctx, getFund, id)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.ReportSlug,
		&i.CreatedAt,
	)
	return i, err
}

const listFunds = `-- name: ListFunds :many
SELECT id, name, currency, report_slug, created_at
FROM fund
ORDER BY id
`

func (q *Queries) ListFunds(ctx context.Context) ([]Fund, error) {
	rows, err := q.db.QueryContext(ctx, listFunds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fund{}
	for rows.Next() {
		var i Fund
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.ReportSlug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFund = `-- name: UpdateFund :one
UPDATE fund
SET name = ?
WHERE id = ?
RETURNING id, name, currency, report_slug, created_at
`

type UpdateFundParams struct {
	Name string
	ID   int64
}

// UpdateFund renames the fund. name is a display label - it heads every
// screen and the public report - and nothing posted references it, so this
// changes no history (the same reasoning UpdateAccount's own rename rests
// on). currency and report_slug are deliberately not settable here: one is
// an invariant through 0.x, the other is the report's unguessable address.
func (q *Queries) UpdateFund(ctx context.Context, arg UpdateFundParams) (Fund, error) {
	row := q.db.QueryRowContext(ctx, updateFund, arg.Name, arg.ID)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.ReportSlug,
		&i.CreatedAt,
	)
	return i, err
}
