// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidental_recipient.sql

package store

import (
	"context"
)

const createIncidentalRecipient = `-- name: CreateIncidentalRecipient :exec
INSERT INTO incidental_recipient (fund_id, purpose_id, member_id)
VALUES (?, ?, ?)
`

type CreateIncidentalRecipientParams struct {
	FundID    int64
	PurposeID int64
	MemberID  int64
}

// The members an envelope is for (ADR-034), never expected to contribute
// themselves. Inserted one row at a time inside Ledger.OpenIncidental's and
// Ledger.SetIncidentalParticipation's own withTx - unscoped validation here,
// the same shape UpdateIncidentalOccasion's own comment argues for: both
// callers already hold a purpose_id (and, for SetIncidentalParticipation, a
// fund_id) proven to belong to the caller's fund by an earlier fund-scoped
// fetch in the same transaction.
func (q *Queries) CreateIncidentalRecipient(ctx context.Context, arg CreateIncidentalRecipientParams) error {
	_, err := q.db.ExecContext(ctx, createIncidentalRecipient, arg.FundID, arg.PurposeID, arg.MemberID)
	return err
}

const deleteIncidentalRecipientsByPurpose = `-- name: DeleteIncidentalRecipientsByPurpose :exec
DELETE FROM incidental_recipient
WHERE purpose_id = ?
`

// The full-replace half of SetIncidentalParticipation (ADR-034): recipients
// are edited like occasion, not accumulated, so setting a new list clears the
// old one first. Unscoped by fund_id for the reason CreateIncidentalRecipient's
// own comment gives - purpose_id already belongs to the caller's fund by the
// time this runs.
func (q *Queries) DeleteIncidentalRecipientsByPurpose(ctx context.Context, purposeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIncidentalRecipientsByPurpose, purposeID)
	return err
}

const listIncidentalRecipients = `-- name: ListIncidentalRecipients :many
SELECT ir.member_id, m.name AS member_name
FROM incidental_recipient ir
JOIN member m ON m.id = ir.member_id
WHERE ir.purpose_id = ?
ORDER BY m.name, m.id
`

type ListIncidentalRecipientsRow struct {
	MemberID   int64
	MemberName string
}

// One envelope's recipients, member name alongside the id so a caller (the
// participation view, the envelope's own detail screen) never has to look
// each one up separately. Ordered by name then id - the same tiebreak
// ListMembersPage uses - rather than insertion order, which carries no
// meaning here (CLAUDE.md's "no primary-key order" rule).
func (q *Queries) ListIncidentalRecipients(ctx context.Context, purposeID int64) ([]ListIncidentalRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentalRecipients, purposeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentalRecipientsRow{}
	for rows.Next() {
		var i ListIncidentalRecipientsRow
		if err := rows.Scan(&i.MemberID, &i.MemberName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentalRecipientsByFund = `-- name: ListIncidentalRecipientsByFund :many
SELECT fund_id, purpose_id, member_id
FROM incidental_recipient
WHERE fund_id = ?
ORDER BY purpose_id, member_id
`

// ListIncidentalRecipientsByFund is the backup export's own read (ADR-012,
// #323): every recipient row across every envelope the fund owns, in its
// own raw columns (fund_id, purpose_id, member_id) rather than
// ListIncidentalRecipients' joined member_name - the export names the
// table's own columns, and a restore reads member_id, not a name. The table
// has no single-column id (its primary key is the (fund_id, purpose_id,
// member_id) triple), so this orders by that triple directly - purely for
// the export's own deterministic byte order.
func (q *Queries) ListIncidentalRecipientsByFund(ctx context.Context, fundID int64) ([]IncidentalRecipient, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentalRecipientsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentalRecipient{}
	for rows.Next() {
		var i IncidentalRecipient
		if err := rows.Scan(&i.FundID, &i.PurposeID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
