// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidental.sql

package store

import (
	"context"
)

const closeIncidental = `-- name: CloseIncidental :one
UPDATE incidental
SET closed_on = ?
WHERE purpose_id = ?
RETURNING purpose_id, occasion, target_amount, opened_on, closed_on, created_at
`

type CloseIncidentalParams struct {
	ClosedOn  *string
	PurposeID int64
}

// Closing an envelope moves no money, so this is an UPDATE rather than a ledger
// entry - incidental carries no immutability trigger for exactly this reason.
func (q *Queries) CloseIncidental(ctx context.Context, arg CloseIncidentalParams) (Incidental, error) {
	row := q.db.QueryRowContext(ctx, closeIncidental, arg.ClosedOn, arg.PurposeID)
	var i Incidental
	err := row.Scan(
		&i.PurposeID,
		&i.Occasion,
		&i.TargetAmount,
		&i.OpenedOn,
		&i.ClosedOn,
		&i.CreatedAt,
	)
	return i, err
}

const createIncidental = `-- name: CreateIncidental :one
INSERT INTO incidental (purpose_id, occasion, target_amount, opened_on, closed_on, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING purpose_id, occasion, target_amount, opened_on, closed_on, created_at
`

type CreateIncidentalParams struct {
	PurposeID    int64
	Occasion     string
	TargetAmount *int64
	OpenedOn     string
	ClosedOn     *string
	CreatedAt    int64
}

func (q *Queries) CreateIncidental(ctx context.Context, arg CreateIncidentalParams) (Incidental, error) {
	row := q.db.QueryRowContext(ctx, createIncidental,
		arg.PurposeID,
		arg.Occasion,
		arg.TargetAmount,
		arg.OpenedOn,
		arg.ClosedOn,
		arg.CreatedAt,
	)
	var i Incidental
	err := row.Scan(
		&i.PurposeID,
		&i.Occasion,
		&i.TargetAmount,
		&i.OpenedOn,
		&i.ClosedOn,
		&i.CreatedAt,
	)
	return i, err
}

const getIncidental = `-- name: GetIncidental :one
SELECT i.purpose_id, i.occasion, i.target_amount, i.opened_on, i.closed_on, i.created_at
FROM incidental i
JOIN purpose p ON p.id = i.purpose_id
WHERE i.purpose_id = ? AND p.fund_id = ?
`

type GetIncidentalParams struct {
	PurposeID int64
	FundID    int64
}

// Fund-scoped through purpose, which is where the envelope's fund_id lives
// (incidental is 1:1 with its purpose row and carries no fund_id of its own).
// An id names a row, it does not prove the caller may see it: PRD section 6 allows a
// server to hold more than one fund, so a bare WHERE purpose_id = ? would be a
// cross-fund read the moment a second fund exists.
func (q *Queries) GetIncidental(ctx context.Context, arg GetIncidentalParams) (Incidental, error) {
	row := q.db.QueryRowContext(ctx, getIncidental, arg.PurposeID, arg.FundID)
	var i Incidental
	err := row.Scan(
		&i.PurposeID,
		&i.Occasion,
		&i.TargetAmount,
		&i.OpenedOn,
		&i.ClosedOn,
		&i.CreatedAt,
	)
	return i, err
}

const listIncidentalsByFund = `-- name: ListIncidentalsByFund :many
SELECT i.purpose_id, i.occasion, i.target_amount, i.opened_on, i.closed_on, i.created_at
FROM incidental i
JOIN purpose p ON p.id = i.purpose_id
WHERE p.fund_id = ?
ORDER BY i.opened_on, i.purpose_id
`

// Joined through purpose because that is where fund ownership lives; incidental
// has no fund_id of its own (it is 1:1 with a purpose row).
func (q *Queries) ListIncidentalsByFund(ctx context.Context, fundID int64) ([]Incidental, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentalsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incidental{}
	for rows.Next() {
		var i Incidental
		if err := rows.Scan(
			&i.PurposeID,
			&i.Occasion,
			&i.TargetAmount,
			&i.OpenedOn,
			&i.ClosedOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIncidentalsByFund = `-- name: ListOpenIncidentalsByFund :many
SELECT i.purpose_id, i.occasion, i.target_amount, i.opened_on, i.closed_on, i.created_at
FROM incidental i
JOIN purpose p ON p.id = i.purpose_id
WHERE p.fund_id = ? AND i.closed_on IS NULL
ORDER BY i.opened_on, i.purpose_id
`

func (q *Queries) ListOpenIncidentalsByFund(ctx context.Context, fundID int64) ([]Incidental, error) {
	rows, err := q.db.QueryContext(ctx, listOpenIncidentalsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incidental{}
	for rows.Next() {
		var i Incidental
		if err := rows.Scan(
			&i.PurposeID,
			&i.Occasion,
			&i.TargetAmount,
			&i.OpenedOn,
			&i.ClosedOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
