// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package store

import (
	"context"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member (fund_id, name, tier_id, joined_on, inactive_on, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, fund_id, name, tier_id, joined_on, inactive_on, created_at
`

type CreateMemberParams struct {
	FundID     int64
	Name       string
	TierID     *int64
	JoinedOn   *string
	InactiveOn *string
	CreatedAt  int64
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember,
		arg.FundID,
		arg.Name,
		arg.TierID,
		arg.JoinedOn,
		arg.InactiveOn,
		arg.CreatedAt,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.TierID,
		&i.JoinedOn,
		&i.InactiveOn,
		&i.CreatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, fund_id, name, tier_id, joined_on, inactive_on, created_at
FROM member
WHERE id = ?
`

func (q *Queries) GetMember(ctx context.Context, id int64) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.TierID,
		&i.JoinedOn,
		&i.InactiveOn,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersByFund = `-- name: ListMembersByFund :many
SELECT id, fund_id, name, tier_id, joined_on, inactive_on, created_at
FROM member
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListMembersByFund(ctx context.Context, fundID int64) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Name,
			&i.TierID,
			&i.JoinedOn,
			&i.InactiveOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
