// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package store

import (
	"context"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member (fund_id, name, tier_id, joined_on, inactive_on, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, fund_id, name, tier_id, joined_on, inactive_on, created_at
`

type CreateMemberParams struct {
	FundID     int64
	Name       string
	TierID     *int64
	JoinedOn   *string
	InactiveOn *string
	CreatedAt  int64
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember,
		arg.FundID,
		arg.Name,
		arg.TierID,
		arg.JoinedOn,
		arg.InactiveOn,
		arg.CreatedAt,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.TierID,
		&i.JoinedOn,
		&i.InactiveOn,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM member
WHERE id = ?
`

// DeleteMember leans on the composite foreign keys from "transaction" and
// reimbursement to refuse it once a real row references the member.
func (q *Queries) DeleteMember(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMember, id)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, fund_id, name, tier_id, joined_on, inactive_on, created_at
FROM member
WHERE id = ?
`

func (q *Queries) GetMember(ctx context.Context, id int64) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.TierID,
		&i.JoinedOn,
		&i.InactiveOn,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberForFund = `-- name: GetMemberForFund :one
SELECT id, fund_id, name, tier_id, joined_on, inactive_on, created_at
FROM member
WHERE id = ? AND fund_id = ?
`

type GetMemberForFundParams struct {
	ID     int64
	FundID int64
}

// GetMemberForFund is GetMember fund-scoped (WHERE fund_id = ? AND id = ?),
// the same shape GetTransactionForFund and GetReimbursement already use: a
// member id that is real but belongs to another fund answers sql.ErrNoRows
// here rather than being found and only then rejected for ownership.
func (q *Queries) GetMemberForFund(ctx context.Context, arg GetMemberForFundParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberForFund, arg.ID, arg.FundID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.TierID,
		&i.JoinedOn,
		&i.InactiveOn,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersByFund = `-- name: ListMembersByFund :many
SELECT id, fund_id, name, tier_id, joined_on, inactive_on, created_at
FROM member
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListMembersByFund(ctx context.Context, fundID int64) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Name,
			&i.TierID,
			&i.JoinedOn,
			&i.InactiveOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE member
SET name        = COALESCE(?1, name),
    tier_id     = CASE WHEN CAST(?2     AS INTEGER) = 1 THEN ?3     ELSE tier_id     END,
    joined_on   = CASE WHEN CAST(?4   AS INTEGER) = 1 THEN ?5   ELSE joined_on   END,
    inactive_on = CASE WHEN CAST(?6 AS INTEGER) = 1 THEN ?7 ELSE inactive_on END
WHERE id = ?8
RETURNING id, fund_id, name, tier_id, joined_on, inactive_on, created_at
`

type UpdateMemberParams struct {
	Name          *string
	SetTierID     int64
	TierID        *int64
	SetJoinedOn   int64
	JoinedOn      *string
	SetInactiveOn int64
	InactiveOn    *string
	ID            int64
}

// UpdateMember is a correction to reference data, not a ledger event. name
// is NOT NULL, so COALESCE covers it: a nil argument can only mean "leave
// alone". The three nullable columns need the set_* flags, because there a
// null argument is ambiguous between "leave alone" and "clear it" - the CASE
// substitutes the new value, NULL included, only when the caller sent it.
func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, updateMember,
		arg.Name,
		arg.SetTierID,
		arg.TierID,
		arg.SetJoinedOn,
		arg.JoinedOn,
		arg.SetInactiveOn,
		arg.InactiveOn,
		arg.ID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Name,
		&i.TierID,
		&i.JoinedOn,
		&i.InactiveOn,
		&i.CreatedAt,
	)
	return i, err
}
