// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Account struct {
	ID        int64
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}

type DuesRate struct {
	ID            int64
	TierID        int64
	Amount        int64
	EffectiveFrom string
	CreatedAt     int64
}

type DuesTier struct {
	ID        int64
	FundID    int64
	Name      string
	CreatedAt int64
}

type Fund struct {
	ID         int64
	Name       string
	Currency   string
	ReportSlug string
	CreatedAt  int64
}

type Incidental struct {
	PurposeID    int64
	Occasion     string
	TargetAmount *int64
	OpenedOn     string
	ClosedOn     *string
	CreatedAt    int64
}

type Member struct {
	ID         int64
	FundID     int64
	Name       string
	TierID     *int64
	JoinedOn   *string
	InactiveOn *string
	CreatedAt  int64
}

type Purpose struct {
	ID        int64
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}

type Receipt struct {
	ID              int64
	FundID          int64
	TransactionID   *int64
	ReimbursementID *int64
	Path            string
	UploadedAt      int64
}

type Reconciliation struct {
	ID                   int64
	FundID               int64
	PerformedAt          int64
	ThroughTransactionID *int64
	Note                 *string
	CreatedAt            int64
}

type ReconciliationLine struct {
	ID                      int64
	FundID                  int64
	ReconciliationID        int64
	AccountID               int64
	RecordedAmount          int64
	ActualAmount            int64
	DifferenceAmount        int64
	Resolution              string
	AdjustmentTransactionID *int64
}

type Reimbursement struct {
	ID         int64
	FundID     int64
	MemberID   int64
	PurposeID  int64
	Amount     int64
	IncurredOn string
	WaivedOn   *string
	Note       *string
	CreatedAt  int64
}

type Session struct {
	Token     string
	Data      []byte
	ExpiresAt int64
}

type Transaction struct {
	ID                    int64
	FundID                int64
	AccountID             int64
	PurposeID             int64
	Direction             string
	Amount                int64
	OccurredOn            string
	Kind                  string
	MemberID              *int64
	DuesPeriod            *string
	ReimbursementID       *int64
	TransferID            *int64
	ReversesTransactionID *int64
	Note                  *string
	CreatedAt             int64
}

type Transfer struct {
	ID        int64
	FundID    int64
	Kind      string
	CreatedAt int64
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    int64
}
