// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Account struct {
	ID        int64
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}

type DuesRate struct {
	ID            int64
	TierID        int64
	Amount        int64
	EffectiveFrom string
	CreatedAt     int64
}

type DuesTier struct {
	ID        int64
	FundID    int64
	Name      string
	CreatedAt int64
}

type Fund struct {
	ID         int64
	Name       string
	Currency   string
	ReportSlug string
	CreatedAt  int64
}

type Member struct {
	ID         int64
	FundID     int64
	Name       string
	TierID     *int64
	JoinedOn   *string
	InactiveOn *string
	CreatedAt  int64
}

type Purpose struct {
	ID        int64
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}
