// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purpose.sql

package store

import (
	"context"
)

const createPurpose = `-- name: CreatePurpose :one
INSERT INTO purpose (fund_id, kind, name, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, fund_id, kind, name, created_at
`

type CreatePurposeParams struct {
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreatePurpose(ctx context.Context, arg CreatePurposeParams) (Purpose, error) {
	row := q.db.QueryRowContext(ctx, createPurpose,
		arg.FundID,
		arg.Kind,
		arg.Name,
		arg.CreatedAt,
	)
	var i Purpose
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getPurpose = `-- name: GetPurpose :one
SELECT id, fund_id, kind, name, created_at
FROM purpose
WHERE id = ?
`

func (q *Queries) GetPurpose(ctx context.Context, id int64) (Purpose, error) {
	row := q.db.QueryRowContext(ctx, getPurpose, id)
	var i Purpose
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listPurposesByFund = `-- name: ListPurposesByFund :many
SELECT id, fund_id, kind, name, created_at
FROM purpose
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListPurposesByFund(ctx context.Context, fundID int64) ([]Purpose, error) {
	rows, err := q.db.QueryContext(ctx, listPurposesByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Purpose{}
	for rows.Next() {
		var i Purpose
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Kind,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
