// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AccountBalance(ctx context.Context, arg AccountBalanceParams) (int64, error)
	// The frozen half of a reconciliation: the same sum as AccountBalance, cut off
	// at the snapshot's through_transaction_id. Ordered by id, not occurred_on, so
	// a correction backdated after the count keeps its higher id and stays outside
	// the old snapshot's arithmetic while counting toward today's balance.
	AccountBalanceThrough(ctx context.Context, arg AccountBalanceThroughParams) (int64, error)
	// Closing an envelope moves no money, so this is an UPDATE rather than a ledger
	// entry - incidental carries no immutability trigger for exactly this reason.
	CloseIncidental(ctx context.Context, arg CloseIncidentalParams) (Incidental, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDuesRate(ctx context.Context, arg CreateDuesRateParams) (DuesRate, error)
	CreateDuesTier(ctx context.Context, arg CreateDuesTierParams) (DuesTier, error)
	CreateFund(ctx context.Context, arg CreateFundParams) (Fund, error)
	CreateIncidental(ctx context.Context, arg CreateIncidentalParams) (Incidental, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreatePurpose(ctx context.Context, arg CreatePurposeParams) (Purpose, error)
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error)
	CreateReconciliation(ctx context.Context, arg CreateReconciliationParams) (Reconciliation, error)
	CreateReconciliationLine(ctx context.Context, arg CreateReconciliationLineParams) (ReconciliationLine, error)
	CreateReimbursement(ctx context.Context, arg CreateReimbursementParams) (Reimbursement, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	// DeleteDuesRate is what makes a wrong-month rate correctable at all, since
	// UNIQUE (tier_id, effective_from) refuses the corrected row otherwise.
	DeleteDuesRate(ctx context.Context, id int64) error
	// DeleteMember leans on the composite foreign keys from "transaction" and
	// reimbursement to refuse it once a real row references the member.
	DeleteMember(ctx context.Context, id int64) error
	// The roster query behind "who has paid / partially / not yet" for one
	// dues_period, across every member in one pass rather than one query per
	// member.
	// The AND NOT EXISTS clause is ADR-029's half of the reversal design: a
	// reversed dues row itself never matched kind = 'dues' in the first place
	// (a reversal is posted as kind='adjustment'), so this drops the ORIGINAL
	// row from the sum once something reverses it - which is what makes a
	// reversed payment disappear from "paid" rather than simply counting twice.
	DuesPaidByPeriod(ctx context.Context, arg DuesPaidByPeriodParams) ([]DuesPaidByPeriodRow, error)
	// Every balance in Uruni is this shape: sum the ledger, never read a stored
	// total (CLAUDE.md rule 2). direction carries the sign, so the CASE is the
	// only place a minus appears. The CAST is not decoration - without it sqlc
	// emits interface{} for the aggregate and the trust core loses its compiler
	// exactly where it is needed most (ADR-024).
	FundBalance(ctx context.Context, fundID int64) (int64, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	// The reversed-once pre-check, same shape as GetReimbursementSettlement and
	// GetOpeningBalance above: sql.ErrNoRows means "not yet reversed, proceed"
	// (the expected, non-error path); a row means it already has been. The
	// dues_payment_reversed_once partial unique index is the actual guarantee -
	// this pre-check only turns a raw constraint violation into a clean, named
	// error (ADR-029, mirroring ADR-027's ErrReimbursementAlreadySettled).
	GetDuesPaymentReversal(ctx context.Context, arg GetDuesPaymentReversalParams) (Transaction, error)
	// GetDuesRate is the lookup PATCH and DELETE both do ahead of the write: an
	// UPDATE's RETURNING would answer an unknown id with sql.ErrNoRows, but a
	// DELETE affecting zero rows raises nothing at all.
	GetDuesRate(ctx context.Context, id int64) (DuesRate, error)
	GetDuesTier(ctx context.Context, id int64) (DuesTier, error)
	// The rate in force for a period: the latest row whose effective_from is at or
	// before it. One-sided intervals mean there is no end date to check, and no
	// row at all is a legitimate answer: a tier whose rate is not yet decided.
	// effective_from is 'YYYY-MM', so a string comparison is a chronological one.
	GetEffectiveDuesRate(ctx context.Context, arg GetEffectiveDuesRateParams) (DuesRate, error)
	GetFund(ctx context.Context, id int64) (Fund, error)
	GetIncidental(ctx context.Context, purposeID int64) (Incidental, error)
	GetMember(ctx context.Context, id int64) (Member, error)
	// The one-opening-per-account pre-check, same shape as
	// GetReimbursementSettlement above: no aggregate, so a fund with no opening
	// entry on this account yet returns a clean sql.ErrNoRows (the expected,
	// non-error path) rather than a NULL forced through an aggregate. A row means
	// one already exists.
	GetOpeningBalance(ctx context.Context, arg GetOpeningBalanceParams) (GetOpeningBalanceRow, error)
	GetPurpose(ctx context.Context, id int64) (Purpose, error)
	GetReconciliation(ctx context.Context, id int64) (Reconciliation, error)
	GetReimbursement(ctx context.Context, id int64) (Reimbursement, error)
	// The settle-once pre-check. Returns sql.ErrNoRows when the claim has not
	// been settled yet (the expected, non-error path) or the settling row when
	// it has.
	GetReimbursementSettlement(ctx context.Context, arg GetReimbursementSettlementParams) (GetReimbursementSettlementRow, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	// The fund-scoped fetch a dues reversal fetches its target through (ADR-029):
	// WHERE fund_id = ? AND id = ?, not id alone, so a transaction belonging to
	// another fund reads as sql.ErrNoRows here rather than being found and only
	// later rejected by the composite FK. GetTransaction above stays as it is -
	// other callers already have their fund-scoped row in hand - this is the one
	// new caller that fetches a transaction by id from an untrusted request.
	GetTransactionForFund(ctx context.Context, arg GetTransactionForFundParams) (Transaction, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	// The two figures PRD 7.5 wants shown side by side for an incidental envelope.
	// Leftover is collected minus disbursed, computed in Go via money.Amount.Sub,
	// rather than a third column here - one aggregate pass over the ledger is
	// enough for both the display figures and the roll amount.
	IncidentalTotals(ctx context.Context, arg IncidentalTotalsParams) (IncidentalTotalsRow, error)
	// The "paid in advance" signal. dues_period is 'YYYY-MM', so a lexicographic
	// MAX is also the chronological one. The CAST(... AS TEXT) is load-bearing,
	// not decoration: uncast, MAX(dues_period) generates interface{} - the same
	// untyped-interface trap ADR-024 documents for SUM, reached here through MAX
	// on a TEXT column - and a .(string) assertion on it is a live panic risk
	// since drivers commonly hand back []byte.
	// The AND NOT EXISTS clause is ADR-029's fix for the specific bug the chosen
	// design exists to avoid: without it, a reversed row would still be the
	// chronological MAX(dues_period) for its member, reading as "paid in
	// advance" through a period that was reversed and is no longer paid at all.
	LatestDuesPeriodPaidByMember(ctx context.Context, fundID int64) ([]LatestDuesPeriodPaidByMemberRow, error)
	LatestReconciliation(ctx context.Context, fundID int64) (Reconciliation, error)
	ListAccountsByFund(ctx context.Context, fundID int64) ([]Account, error)
	ListDuesPaymentsByMember(ctx context.Context, memberID *int64) ([]ListDuesPaymentsByMemberRow, error)
	ListDuesRatesByTier(ctx context.Context, tierID int64) ([]DuesRate, error)
	ListDuesTiersByFund(ctx context.Context, fundID int64) ([]DuesTier, error)
	ListFunds(ctx context.Context) ([]Fund, error)
	// Joined through purpose because that is where fund ownership lives; incidental
	// has no fund_id of its own (it is 1:1 with a purpose row).
	ListIncidentalsByFund(ctx context.Context, fundID int64) ([]Incidental, error)
	ListMembersByFund(ctx context.Context, fundID int64) ([]Member, error)
	ListOpenIncidentalsByFund(ctx context.Context, fundID int64) ([]Incidental, error)
	// Differences the treasurer chose to sleep on. They are not errors, and the
	// next snapshot is where they get picked up again - a line is never edited.
	ListOpenReconciliationLinesByFund(ctx context.Context, fundID int64) ([]ReconciliationLine, error)
	// What the fund still owes its members: neither settled by a payout nor
	// waived. Both halves are conditions SQLite cannot express as a CHECK across
	// tables, so the settle path filters on them here instead.
	ListOutstandingReimbursementsByFund(ctx context.Context, fundID int64) ([]Reimbursement, error)
	ListPurposesByFund(ctx context.Context, fundID int64) ([]Purpose, error)
	ListReceiptsByReimbursement(ctx context.Context, reimbursementID *int64) ([]Receipt, error)
	ListReceiptsByTransaction(ctx context.Context, transactionID *int64) ([]Receipt, error)
	ListReconciliationLines(ctx context.Context, reconciliationID int64) ([]ReconciliationLine, error)
	// Newest first: the home screen wants the last count, not the first.
	ListReconciliationsByFund(ctx context.Context, fundID int64) ([]Reconciliation, error)
	ListReimbursementsByFund(ctx context.Context, fundID int64) ([]Reimbursement, error)
	ListTransactionsByFund(ctx context.Context, fundID int64) ([]Transaction, error)
	ListTransfersByFund(ctx context.Context, fundID int64) ([]Transfer, error)
	// The reconciliation cutoff. Deliberately not an aggregate: SELECT
	// CAST(MAX(id) AS INTEGER) generates a non-nullable (int64, error), and a
	// bare aggregate with no GROUP BY still returns one row on an empty table
	// with the value NULL - so a fund's first-ever reconciliation would fail
	// with "converting NULL to int64 is unsupported". This form returns zero
	// rows instead, giving a clean sql.ErrNoRows the domain reads as "no ledger
	// yet".
	MaxTransactionIDByFund(ctx context.Context, fundID int64) (int64, error)
	// The outstanding total, cast so it lands as int64 rather than interface{}:
	// sqlc's SQLite engine cannot infer the type of a summed expression, and an
	// uncast aggregate is a silent failure that only surfaces at M3 (ADR-024).
	OutstandingReimbursementTotal(ctx context.Context, fundID int64) (int64, error)
	// Ping proves the store is reachable through the generated code (open,
	// migrate, query) without naming a table, which M1.3 deliberately has none of.
	// Every real query arrives with the schema at M2; this one stays as the
	// readiness probe /healthz calls.
	//
	// Every comment in this directory is pure ASCII, and that is load-bearing:
	// sqlc v1.31.1's SQLite engine measures a statement's end in runes but slices
	// the source in bytes, so each non-ASCII character in a query's leading
	// comment silently chops one more byte off the tail of the generated constant.
	// Three em dashes here used to cost six bytes, leaving `SELECT 1` where
	// `SELECT 1 AS ok` was written; it still ran, which is what makes it
	// dangerous. `LIMIT 1` losing its `1` does not. See ADR-024 and ADR-005.
	Ping(ctx context.Context) (int64, error)
	PurposeBalance(ctx context.Context, arg PurposeBalanceParams) (int64, error)
	// Whether the fund as a whole came out even. Cast so the trust core gets an
	// int64 rather than interface{} - sqlc's SQLite engine cannot infer the type of
	// a summed expression (ADR-024).
	ReconciliationDifferenceTotal(ctx context.Context, reconciliationID int64) (int64, error)
	// UpdateDuesRate corrects a mistyped amount. effective_from stays fixed: a
	// rate filed against the wrong month is deleted and re-posted, not moved.
	UpdateDuesRate(ctx context.Context, arg UpdateDuesRateParams) (DuesRate, error)
	// UpdateDuesTier renames a tier - reference data, not history.
	UpdateDuesTier(ctx context.Context, arg UpdateDuesTierParams) (DuesTier, error)
	// UpdateMember is a correction to reference data, not a ledger event. name
	// is NOT NULL, so COALESCE covers it: a nil argument can only mean "leave
	// alone". The three nullable columns need the set_* flags, because there a
	// null argument is ambiguous between "leave alone" and "clear it" - the CASE
	// substitutes the new value, NULL included, only when the caller sent it.
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
}

var _ Querier = (*Queries)(nil)
