// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt.sql

package store

import (
	"context"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipt (fund_id, transaction_id, reimbursement_id, path, uploaded_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, fund_id, transaction_id, reimbursement_id, path, uploaded_at
`

type CreateReceiptParams struct {
	FundID          int64
	TransactionID   *int64
	ReimbursementID *int64
	Path            string
	UploadedAt      int64
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt,
		arg.FundID,
		arg.TransactionID,
		arg.ReimbursementID,
		arg.Path,
		arg.UploadedAt,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.TransactionID,
		&i.ReimbursementID,
		&i.Path,
		&i.UploadedAt,
	)
	return i, err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipt
WHERE id = ?
`

// DeleteReceipt removes a wrong or duplicate photo - ADR-011 states plainly
// that "a wrong photo is replaceable" and `receipt` rows are insertable and
// deletable, unlike a ledger row. Scoped by id alone, the same shape as
// DeleteAccount and DeleteReimbursement: the caller already fund-scoped the
// row through GetReceiptForFund above before reaching this. It removes only
// the database row - the file on disk is left in place; see
// internal/http/receipts.go's own comment for why (ADR-011 already accepts
// the orphan as cheaper than a transactional delete).
func (q *Queries) DeleteReceipt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReceipt, id)
	return err
}

const getReceiptForFund = `-- name: GetReceiptForFund :one
SELECT id, fund_id, transaction_id, reimbursement_id, path, uploaded_at
FROM receipt
WHERE id = ? AND fund_id = ?
`

type GetReceiptForFundParams struct {
	ID     int64
	FundID int64
}

// Fund-scoped fetch, the same shape as GetAccountForFund/GetReimbursement:
// an id names a row, not permission to see it - and a receipt is the one
// resource this API serves as raw bytes, so this is the only gate between a
// session and someone else's photo (#153).
func (q *Queries) GetReceiptForFund(ctx context.Context, arg GetReceiptForFundParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptForFund, arg.ID, arg.FundID)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.TransactionID,
		&i.ReimbursementID,
		&i.Path,
		&i.UploadedAt,
	)
	return i, err
}

const listReceiptsByReimbursement = `-- name: ListReceiptsByReimbursement :many
SELECT id, fund_id, transaction_id, reimbursement_id, path, uploaded_at
FROM receipt
WHERE reimbursement_id = ?
ORDER BY id
`

func (q *Queries) ListReceiptsByReimbursement(ctx context.Context, reimbursementID *int64) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByReimbursement, reimbursementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.TransactionID,
			&i.ReimbursementID,
			&i.Path,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByTransaction = `-- name: ListReceiptsByTransaction :many
SELECT id, fund_id, transaction_id, reimbursement_id, path, uploaded_at
FROM receipt
WHERE transaction_id = ?
ORDER BY id
`

func (q *Queries) ListReceiptsByTransaction(ctx context.Context, transactionID *int64) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.TransactionID,
			&i.ReimbursementID,
			&i.Path,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
