// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package store

import (
	"context"
)

const createReconciliation = `-- name: CreateReconciliation :one
INSERT INTO reconciliation (fund_id, performed_at, through_transaction_id, note, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, fund_id, performed_at, through_transaction_id, note, created_at
`

type CreateReconciliationParams struct {
	FundID               int64
	PerformedAt          int64
	ThroughTransactionID *int64
	Note                 *string
	CreatedAt            int64
}

func (q *Queries) CreateReconciliation(ctx context.Context, arg CreateReconciliationParams) (Reconciliation, error) {
	row := q.db.QueryRowContext(ctx, createReconciliation,
		arg.FundID,
		arg.PerformedAt,
		arg.ThroughTransactionID,
		arg.Note,
		arg.CreatedAt,
	)
	var i Reconciliation
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.PerformedAt,
		&i.ThroughTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getReconciliation = `-- name: GetReconciliation :one
SELECT id, fund_id, performed_at, through_transaction_id, note, created_at
FROM reconciliation
WHERE id = ?
`

func (q *Queries) GetReconciliation(ctx context.Context, id int64) (Reconciliation, error) {
	row := q.db.QueryRowContext(ctx, getReconciliation, id)
	var i Reconciliation
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.PerformedAt,
		&i.ThroughTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const latestReconciliation = `-- name: LatestReconciliation :one
SELECT id, fund_id, performed_at, through_transaction_id, note, created_at
FROM reconciliation
WHERE fund_id = ?
ORDER BY performed_at DESC, id DESC
LIMIT 1
`

func (q *Queries) LatestReconciliation(ctx context.Context, fundID int64) (Reconciliation, error) {
	row := q.db.QueryRowContext(ctx, latestReconciliation, fundID)
	var i Reconciliation
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.PerformedAt,
		&i.ThroughTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listReconciliationsByFund = `-- name: ListReconciliationsByFund :many
SELECT id, fund_id, performed_at, through_transaction_id, note, created_at
FROM reconciliation
WHERE fund_id = ?
ORDER BY performed_at DESC, id DESC
`

// Newest first: the home screen wants the last count, not the first.
func (q *Queries) ListReconciliationsByFund(ctx context.Context, fundID int64) ([]Reconciliation, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reconciliation{}
	for rows.Next() {
		var i Reconciliation
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.PerformedAt,
			&i.ThroughTransactionID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
