// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package store

import (
	"context"
)

const createReconciliation = `-- name: CreateReconciliation :one
INSERT INTO reconciliation (fund_id, performed_at, through_transaction_id, note, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, fund_id, performed_at, through_transaction_id, note, created_at
`

type CreateReconciliationParams struct {
	FundID               int64
	PerformedAt          int64
	ThroughTransactionID *int64
	Note                 *string
	CreatedAt            int64
}

func (q *Queries) CreateReconciliation(ctx context.Context, arg CreateReconciliationParams) (Reconciliation, error) {
	row := q.db.QueryRowContext(ctx, createReconciliation,
		arg.FundID,
		arg.PerformedAt,
		arg.ThroughTransactionID,
		arg.Note,
		arg.CreatedAt,
	)
	var i Reconciliation
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.PerformedAt,
		&i.ThroughTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getReconciliation = `-- name: GetReconciliation :one
SELECT id, fund_id, performed_at, through_transaction_id, note, created_at
FROM reconciliation
WHERE id = ? AND fund_id = ?
`

type GetReconciliationParams struct {
	ID     int64
	FundID int64
}

// Fund-scoped: an id names a row, it does not prove the caller may see it.
// PRD section 6 allows a server to hold more than one fund, so a bare lookup
// by id alone would be a cross-fund read the moment a second fund exists.
func (q *Queries) GetReconciliation(ctx context.Context, arg GetReconciliationParams) (Reconciliation, error) {
	row := q.db.QueryRowContext(ctx, getReconciliation, arg.ID, arg.FundID)
	var i Reconciliation
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.PerformedAt,
		&i.ThroughTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const latestReconciliation = `-- name: LatestReconciliation :one
SELECT id, fund_id, performed_at, through_transaction_id, note, created_at
FROM reconciliation
WHERE fund_id = ?
ORDER BY performed_at DESC, id DESC
LIMIT 1
`

func (q *Queries) LatestReconciliation(ctx context.Context, fundID int64) (Reconciliation, error) {
	row := q.db.QueryRowContext(ctx, latestReconciliation, fundID)
	var i Reconciliation
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.PerformedAt,
		&i.ThroughTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listReconciliationsByFund = `-- name: ListReconciliationsByFund :many
SELECT id, fund_id, performed_at, through_transaction_id, note, created_at
FROM reconciliation
WHERE fund_id = ?
ORDER BY performed_at DESC, id DESC
`

// Newest first: the home screen wants the last count, not the first.
func (q *Queries) ListReconciliationsByFund(ctx context.Context, fundID int64) ([]Reconciliation, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reconciliation{}
	for rows.Next() {
		var i Reconciliation
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.PerformedAt,
			&i.ThroughTransactionID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationsPage = `-- name: ListReconciliationsPage :many
SELECT r.id, r.fund_id, r.performed_at, r.through_transaction_id, r.note, r.created_at,
  CAST(COALESCE((
    SELECT SUM(ABS(rl.difference_amount))
    FROM reconciliation_line rl
    WHERE rl.reconciliation_id = r.id AND rl.resolution = 'left_open'
  ), 0) AS INTEGER) AS open_difference_amount
FROM reconciliation r
WHERE r.fund_id = ?1
  AND (
    ?2 IS NULL
    OR (r.performed_at, r.id) < (?2, CAST(?3 AS INTEGER))
  )
ORDER BY r.performed_at DESC, r.id DESC
LIMIT ?4
`

type ListReconciliationsPageParams struct {
	FundID            int64
	CursorPerformedAt interface{}
	CursorID          *int64
	PageLimit         int64
}

type ListReconciliationsPageRow struct {
	ID                   int64
	FundID               int64
	PerformedAt          int64
	ThroughTransactionID *int64
	Note                 *string
	CreatedAt            int64
	OpenDifferenceAmount int64
}

// GET /api/reconciliations's real listing (#227, ADR-032 "Lists: paging and
// search") - newest-first and keyset-paged on (performed_at, id), the same
// row-value-keyset shape ListReimbursementsPage/ListTransactionsPage use
// (their own comments have the full reasoning). No search - a handful of
// dated snapshots a year, per the issue.
//
// open_difference_amount is the sum of ABS(difference_amount) across that
// snapshot's still-open lines - the same figure Confirmation on /reconcile
// computes client-side from a detail fetch, computed here so a list row can
// show cocok (0) vs selisih without one. Cast so it lands as int64 rather
// than interface{} - sqlc's SQLite engine cannot infer the type of a summed
// expression (ADR-024).
//
// page_limit is page size + 1, the same "peek at one extra row" trick the
// other two paged lists use.
func (q *Queries) ListReconciliationsPage(ctx context.Context, arg ListReconciliationsPageParams) ([]ListReconciliationsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationsPage,
		arg.FundID,
		arg.CursorPerformedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationsPageRow{}
	for rows.Next() {
		var i ListReconciliationsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.PerformedAt,
			&i.ThroughTransactionID,
			&i.Note,
			&i.CreatedAt,
			&i.OpenDifferenceAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
