// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation_line.sql

package store

import (
	"context"
)

const createReconciliationLine = `-- name: CreateReconciliationLine :one
INSERT INTO reconciliation_line (
  fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
  difference_amount, resolution, adjustment_transaction_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
          difference_amount, resolution, adjustment_transaction_id
`

type CreateReconciliationLineParams struct {
	FundID                  int64
	ReconciliationID        int64
	AccountID               int64
	RecordedAmount          int64
	ActualAmount            int64
	DifferenceAmount        int64
	Resolution              string
	AdjustmentTransactionID *int64
}

func (q *Queries) CreateReconciliationLine(ctx context.Context, arg CreateReconciliationLineParams) (ReconciliationLine, error) {
	row := q.db.QueryRowContext(ctx, createReconciliationLine,
		arg.FundID,
		arg.ReconciliationID,
		arg.AccountID,
		arg.RecordedAmount,
		arg.ActualAmount,
		arg.DifferenceAmount,
		arg.Resolution,
		arg.AdjustmentTransactionID,
	)
	var i ReconciliationLine
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.ReconciliationID,
		&i.AccountID,
		&i.RecordedAmount,
		&i.ActualAmount,
		&i.DifferenceAmount,
		&i.Resolution,
		&i.AdjustmentTransactionID,
	)
	return i, err
}

const listOpenReconciliationLinesByFund = `-- name: ListOpenReconciliationLinesByFund :many
SELECT rl.id, rl.fund_id, rl.reconciliation_id, rl.account_id, rl.recorded_amount,
       rl.actual_amount, rl.difference_amount, rl.resolution, rl.adjustment_transaction_id
FROM reconciliation_line rl
JOIN reconciliation r ON r.fund_id = rl.fund_id AND r.id = rl.reconciliation_id
WHERE rl.fund_id = ?
  AND rl.resolution = 'left_open'
  AND NOT EXISTS (
    SELECT 1
    FROM reconciliation_line rl2
    JOIN reconciliation r2 ON r2.fund_id = rl2.fund_id AND r2.id = rl2.reconciliation_id
    WHERE rl2.fund_id = rl.fund_id
      AND rl2.account_id = rl.account_id
      AND (r2.performed_at > r.performed_at
           OR (r2.performed_at = r.performed_at AND r2.id > r.id))
  )
ORDER BY r.performed_at, r.id, rl.account_id
`

// Differences the treasurer chose to sleep on, but only while nothing later
// has weighed in on the same location. A left_open line stops counting as
// open the moment a later snapshot has any line at all for that account_id -
// matched, entry_added, adjusted, or left_open again all supersede it, since
// the question is only "has this location been counted since", not how that
// count came out. This is per location, not per snapshot: a later count that
// skips an account leaves that account's gap open regardless of what else the
// later snapshot resolved. "Later" means the owning reconciliation's
// (performed_at, id), performed_at first - a snapshot is never edited
// (ADR-024), so a superseded line stays in the table exactly as recorded; it
// just stops being "open".
func (q *Queries) ListOpenReconciliationLinesByFund(ctx context.Context, fundID int64) ([]ReconciliationLine, error) {
	rows, err := q.db.QueryContext(ctx, listOpenReconciliationLinesByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationLine{}
	for rows.Next() {
		var i ReconciliationLine
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.ReconciliationID,
			&i.AccountID,
			&i.RecordedAmount,
			&i.ActualAmount,
			&i.DifferenceAmount,
			&i.Resolution,
			&i.AdjustmentTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationLines = `-- name: ListReconciliationLines :many
SELECT id, fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
       difference_amount, resolution, adjustment_transaction_id
FROM reconciliation_line
WHERE reconciliation_id = ?
ORDER BY account_id
`

func (q *Queries) ListReconciliationLines(ctx context.Context, reconciliationID int64) ([]ReconciliationLine, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationLines, reconciliationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationLine{}
	for rows.Next() {
		var i ReconciliationLine
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.ReconciliationID,
			&i.AccountID,
			&i.RecordedAmount,
			&i.ActualAmount,
			&i.DifferenceAmount,
			&i.Resolution,
			&i.AdjustmentTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconciliationDifferenceTotal = `-- name: ReconciliationDifferenceTotal :one
SELECT CAST(COALESCE(SUM(difference_amount), 0) AS INTEGER) AS difference_amount
FROM reconciliation_line
WHERE reconciliation_id = ?
`

// Whether the fund as a whole came out even. Cast so the trust core gets an
// int64 rather than interface{} - sqlc's SQLite engine cannot infer the type of
// a summed expression (ADR-024).
func (q *Queries) ReconciliationDifferenceTotal(ctx context.Context, reconciliationID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, reconciliationDifferenceTotal, reconciliationID)
	var difference_amount int64
	err := row.Scan(&difference_amount)
	return difference_amount, err
}
