// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation_line.sql

package store

import (
	"context"
)

const createReconciliationLine = `-- name: CreateReconciliationLine :one
INSERT INTO reconciliation_line (
  fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
  difference_amount, resolution, adjustment_transaction_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
          difference_amount, resolution, adjustment_transaction_id
`

type CreateReconciliationLineParams struct {
	FundID                  int64
	ReconciliationID        int64
	AccountID               int64
	RecordedAmount          int64
	ActualAmount            int64
	DifferenceAmount        int64
	Resolution              string
	AdjustmentTransactionID *int64
}

func (q *Queries) CreateReconciliationLine(ctx context.Context, arg CreateReconciliationLineParams) (ReconciliationLine, error) {
	row := q.db.QueryRowContext(ctx, createReconciliationLine,
		arg.FundID,
		arg.ReconciliationID,
		arg.AccountID,
		arg.RecordedAmount,
		arg.ActualAmount,
		arg.DifferenceAmount,
		arg.Resolution,
		arg.AdjustmentTransactionID,
	)
	var i ReconciliationLine
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.ReconciliationID,
		&i.AccountID,
		&i.RecordedAmount,
		&i.ActualAmount,
		&i.DifferenceAmount,
		&i.Resolution,
		&i.AdjustmentTransactionID,
	)
	return i, err
}

const listOpenReconciliationLinesByFund = `-- name: ListOpenReconciliationLinesByFund :many
SELECT id, fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
       difference_amount, resolution, adjustment_transaction_id
FROM reconciliation_line
WHERE fund_id = ? AND resolution = 'left_open'
ORDER BY reconciliation_id, account_id
`

// Differences the treasurer chose to sleep on. They are not errors, and the
// next snapshot is where they get picked up again - a line is never edited.
func (q *Queries) ListOpenReconciliationLinesByFund(ctx context.Context, fundID int64) ([]ReconciliationLine, error) {
	rows, err := q.db.QueryContext(ctx, listOpenReconciliationLinesByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationLine{}
	for rows.Next() {
		var i ReconciliationLine
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.ReconciliationID,
			&i.AccountID,
			&i.RecordedAmount,
			&i.ActualAmount,
			&i.DifferenceAmount,
			&i.Resolution,
			&i.AdjustmentTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationLines = `-- name: ListReconciliationLines :many
SELECT id, fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
       difference_amount, resolution, adjustment_transaction_id
FROM reconciliation_line
WHERE reconciliation_id = ?
ORDER BY account_id
`

func (q *Queries) ListReconciliationLines(ctx context.Context, reconciliationID int64) ([]ReconciliationLine, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationLines, reconciliationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationLine{}
	for rows.Next() {
		var i ReconciliationLine
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.ReconciliationID,
			&i.AccountID,
			&i.RecordedAmount,
			&i.ActualAmount,
			&i.DifferenceAmount,
			&i.Resolution,
			&i.AdjustmentTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconciliationDifferenceTotal = `-- name: ReconciliationDifferenceTotal :one
SELECT CAST(COALESCE(SUM(difference_amount), 0) AS INTEGER) AS difference_amount
FROM reconciliation_line
WHERE reconciliation_id = ?
`

// Whether the fund as a whole came out even. Cast so the trust core gets an
// int64 rather than interface{} - sqlc's SQLite engine cannot infer the type of
// a summed expression (ADR-024).
func (q *Queries) ReconciliationDifferenceTotal(ctx context.Context, reconciliationID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, reconciliationDifferenceTotal, reconciliationID)
	var difference_amount int64
	err := row.Scan(&difference_amount)
	return difference_amount, err
}
