// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reimbursement.sql

package store

import (
	"context"
)

const createReimbursement = `-- name: CreateReimbursement :one
INSERT INTO reimbursement (fund_id, member_id, purpose_id, amount, incurred_on, waived_on, note, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, fund_id, member_id, purpose_id, amount, incurred_on, waived_on, note, created_at
`

type CreateReimbursementParams struct {
	FundID     int64
	MemberID   int64
	PurposeID  int64
	Amount     int64
	IncurredOn string
	WaivedOn   *string
	Note       *string
	CreatedAt  int64
}

func (q *Queries) CreateReimbursement(ctx context.Context, arg CreateReimbursementParams) (Reimbursement, error) {
	row := q.db.QueryRowContext(ctx, createReimbursement,
		arg.FundID,
		arg.MemberID,
		arg.PurposeID,
		arg.Amount,
		arg.IncurredOn,
		arg.WaivedOn,
		arg.Note,
		arg.CreatedAt,
	)
	var i Reimbursement
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.MemberID,
		&i.PurposeID,
		&i.Amount,
		&i.IncurredOn,
		&i.WaivedOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReimbursement = `-- name: DeleteReimbursement :exec
DELETE FROM reimbursement
WHERE id = ?
`

// DeleteReimbursement removes a claim that should never have existed. It
// leans on receipt's composite foreign key to refuse a claim that still has
// a photo attached, the same way DeleteMember leans on its referencing
// tables; the settled check is internal/ledger's, above.
func (q *Queries) DeleteReimbursement(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReimbursement, id)
	return err
}

const getReimbursement = `-- name: GetReimbursement :one
SELECT id, fund_id, member_id, purpose_id, amount, incurred_on, waived_on, note, created_at
FROM reimbursement
WHERE id = ? AND fund_id = ?
`

type GetReimbursementParams struct {
	ID     int64
	FundID int64
}

// Fund-scoped on purpose: an id names a row, it does not prove the caller may
// see it. PRD section 6 allows a server to hold more than one fund, so a bare
// lookup by id alone would be a cross-fund read the moment a second fund
// exists.
func (q *Queries) GetReimbursement(ctx context.Context, arg GetReimbursementParams) (Reimbursement, error) {
	row := q.db.QueryRowContext(ctx, getReimbursement, arg.ID, arg.FundID)
	var i Reimbursement
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.MemberID,
		&i.PurposeID,
		&i.Amount,
		&i.IncurredOn,
		&i.WaivedOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listOutstandingReimbursementsByFund = `-- name: ListOutstandingReimbursementsByFund :many
SELECT r.id, r.fund_id, r.member_id, r.purpose_id, r.amount, r.incurred_on, r.waived_on, r.note, r.created_at
FROM reimbursement r
WHERE r.fund_id = ?
  AND r.waived_on IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "transaction" t
    WHERE t.reimbursement_id = r.id AND t.kind = 'reimbursement'
  )
ORDER BY r.id
`

// What the fund still owes its members: neither settled by a payout nor
// waived. Both halves are conditions SQLite cannot express as a CHECK across
// tables, so the settle path filters on them here instead.
func (q *Queries) ListOutstandingReimbursementsByFund(ctx context.Context, fundID int64) ([]Reimbursement, error) {
	rows, err := q.db.QueryContext(ctx, listOutstandingReimbursementsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reimbursement{}
	for rows.Next() {
		var i Reimbursement
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.MemberID,
			&i.PurposeID,
			&i.Amount,
			&i.IncurredOn,
			&i.WaivedOn,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReimbursementsByFund = `-- name: ListReimbursementsByFund :many
SELECT id, fund_id, member_id, purpose_id, amount, incurred_on, waived_on, note, created_at
FROM reimbursement
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListReimbursementsByFund(ctx context.Context, fundID int64) ([]Reimbursement, error) {
	rows, err := q.db.QueryContext(ctx, listReimbursementsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reimbursement{}
	for rows.Next() {
		var i Reimbursement
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.MemberID,
			&i.PurposeID,
			&i.Amount,
			&i.IncurredOn,
			&i.WaivedOn,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outstandingReimbursementTotal = `-- name: OutstandingReimbursementTotal :one
SELECT CAST(COALESCE(SUM(r.amount), 0) AS INTEGER) AS total_amount
FROM reimbursement r
WHERE r.fund_id = ?
  AND r.waived_on IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "transaction" t
    WHERE t.reimbursement_id = r.id AND t.kind = 'reimbursement'
  )
`

// The outstanding total, cast so it lands as int64 rather than interface{}:
// sqlc's SQLite engine cannot infer the type of a summed expression, and an
// uncast aggregate is a silent failure that only surfaces at M3 (ADR-024).
func (q *Queries) OutstandingReimbursementTotal(ctx context.Context, fundID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, outstandingReimbursementTotal, fundID)
	var total_amount int64
	err := row.Scan(&total_amount)
	return total_amount, err
}

const updateReimbursement = `-- name: UpdateReimbursement :one
UPDATE reimbursement
SET member_id   = COALESCE(?1, member_id),
    purpose_id  = COALESCE(?2, purpose_id),
    amount      = COALESCE(?3, amount),
    incurred_on = COALESCE(?4, incurred_on),
    note        = CASE WHEN CAST(?5      AS INTEGER) = 1 THEN ?6      ELSE note      END,
    waived_on   = CASE WHEN CAST(?7 AS INTEGER) = 1 THEN ?8 ELSE waived_on END
WHERE id = ?9
RETURNING id, fund_id, member_id, purpose_id, amount, incurred_on, waived_on, note, created_at
`

type UpdateReimbursementParams struct {
	MemberID    *int64
	PurposeID   *int64
	Amount      *int64
	IncurredOn  *string
	SetNote     int64
	Note        *string
	SetWaivedOn int64
	WaivedOn    *string
	ID          int64
}

// UpdateReimbursement corrects a claim that has not been settled yet - a
// wrong amount, the wrong member, or the day it was actually spent. The
// claim is off the ledger until it is settled (ADR-024), so this is an
// UPDATE and not an adjusting entry; the settled check that keeps it that
// way lives in internal/ledger, because it reads another table.
//
// waived_on rides on the same statement rather than a route of its own:
// waiving is one column, and pairing it with the ordinary correction is
// what makes un-waiving free. Same COALESCE/set_* split as UpdateMember -
// the four NOT NULL columns cannot mean "clear it", the two nullable ones
// can, and only a set_* flag can tell that from "leave alone".
func (q *Queries) UpdateReimbursement(ctx context.Context, arg UpdateReimbursementParams) (Reimbursement, error) {
	row := q.db.QueryRowContext(ctx, updateReimbursement,
		arg.MemberID,
		arg.PurposeID,
		arg.Amount,
		arg.IncurredOn,
		arg.SetNote,
		arg.Note,
		arg.SetWaivedOn,
		arg.WaivedOn,
		arg.ID,
	)
	var i Reimbursement
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.MemberID,
		&i.PurposeID,
		&i.Amount,
		&i.IncurredOn,
		&i.WaivedOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
