// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restore.sql

package store

import (
	"context"
)

const deleteAllAccounts = `-- name: DeleteAllAccounts :exec
DELETE FROM account
`

func (q *Queries) DeleteAllAccounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAccounts)
	return err
}

const deleteAllDuesRates = `-- name: DeleteAllDuesRates :exec
DELETE FROM dues_rate
`

func (q *Queries) DeleteAllDuesRates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDuesRates)
	return err
}

const deleteAllDuesTiers = `-- name: DeleteAllDuesTiers :exec
DELETE FROM dues_tier
`

func (q *Queries) DeleteAllDuesTiers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDuesTiers)
	return err
}

const deleteAllFunds = `-- name: DeleteAllFunds :exec

DELETE FROM fund
`

// Restore's own queries (M6.39, #325, ADR-012): every table this package's
// normal Create* queries also cover, plus two restore only needs. A normal
// Create* never takes id - the schema assigns it - so restore, which must
// preserve every id verbatim (ADR-012's obligation 2), needs its own insert
// naming id explicitly instead of reusing them. The DeleteAll* queries are
// restore's other own need: clearing a table in full before re-inserting
// exactly what the file holds, the same "delete all sessions" shape
// DeleteAllSessions (session.sql) already established for a password reset.
//
// Table order below follows Document's own field order (internal/backup/
// backup.go), itself the migration file's dependency order - not because
// these statements must run in that order (internal/backup/restore.go's own
// comment says why they need not), but so this file reads the same way the
// schema and the export already do.
func (q *Queries) DeleteAllFunds(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFunds)
	return err
}

const deleteAllIncidentalRecipients = `-- name: DeleteAllIncidentalRecipients :exec
DELETE FROM incidental_recipient
`

func (q *Queries) DeleteAllIncidentalRecipients(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIncidentalRecipients)
	return err
}

const deleteAllIncidentals = `-- name: DeleteAllIncidentals :exec
DELETE FROM incidental
`

func (q *Queries) DeleteAllIncidentals(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIncidentals)
	return err
}

const deleteAllMembers = `-- name: DeleteAllMembers :exec
DELETE FROM member
`

func (q *Queries) DeleteAllMembers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMembers)
	return err
}

const deleteAllPurposes = `-- name: DeleteAllPurposes :exec
DELETE FROM purpose
`

func (q *Queries) DeleteAllPurposes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPurposes)
	return err
}

const deleteAllReceipts = `-- name: DeleteAllReceipts :exec
DELETE FROM receipt
`

func (q *Queries) DeleteAllReceipts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllReceipts)
	return err
}

const deleteAllReconciliationLines = `-- name: DeleteAllReconciliationLines :exec
DELETE FROM reconciliation_line
`

func (q *Queries) DeleteAllReconciliationLines(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllReconciliationLines)
	return err
}

const deleteAllReconciliations = `-- name: DeleteAllReconciliations :exec
DELETE FROM reconciliation
`

func (q *Queries) DeleteAllReconciliations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllReconciliations)
	return err
}

const deleteAllReimbursements = `-- name: DeleteAllReimbursements :exec
DELETE FROM reimbursement
`

func (q *Queries) DeleteAllReimbursements(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllReimbursements)
	return err
}

const deleteAllTransactions = `-- name: DeleteAllTransactions :exec
DELETE FROM "transaction"
`

func (q *Queries) DeleteAllTransactions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTransactions)
	return err
}

const deleteAllTransfers = `-- name: DeleteAllTransfers :exec
DELETE FROM transfer
`

func (q *Queries) DeleteAllTransfers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTransfers)
	return err
}

const restoreAccount = `-- name: RestoreAccount :exec
INSERT INTO account (id, fund_id, kind, name, created_at, inactive_on)
VALUES (?, ?, ?, ?, ?, ?)
`

type RestoreAccountParams struct {
	ID         int64
	FundID     int64
	Kind       string
	Name       string
	CreatedAt  int64
	InactiveOn *string
}

func (q *Queries) RestoreAccount(ctx context.Context, arg RestoreAccountParams) error {
	_, err := q.db.ExecContext(ctx, restoreAccount,
		arg.ID,
		arg.FundID,
		arg.Kind,
		arg.Name,
		arg.CreatedAt,
		arg.InactiveOn,
	)
	return err
}

const restoreDuesRate = `-- name: RestoreDuesRate :exec
INSERT INTO dues_rate (id, tier_id, amount, effective_from, created_at)
VALUES (?, ?, ?, ?, ?)
`

type RestoreDuesRateParams struct {
	ID            int64
	TierID        int64
	Amount        int64
	EffectiveFrom string
	CreatedAt     int64
}

func (q *Queries) RestoreDuesRate(ctx context.Context, arg RestoreDuesRateParams) error {
	_, err := q.db.ExecContext(ctx, restoreDuesRate,
		arg.ID,
		arg.TierID,
		arg.Amount,
		arg.EffectiveFrom,
		arg.CreatedAt,
	)
	return err
}

const restoreDuesTier = `-- name: RestoreDuesTier :exec
INSERT INTO dues_tier (id, fund_id, name, created_at)
VALUES (?, ?, ?, ?)
`

type RestoreDuesTierParams struct {
	ID        int64
	FundID    int64
	Name      string
	CreatedAt int64
}

func (q *Queries) RestoreDuesTier(ctx context.Context, arg RestoreDuesTierParams) error {
	_, err := q.db.ExecContext(ctx, restoreDuesTier,
		arg.ID,
		arg.FundID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const restoreFund = `-- name: RestoreFund :exec
INSERT INTO fund (id, name, currency, report_slug, created_at)
VALUES (?, ?, ?, ?, ?)
`

type RestoreFundParams struct {
	ID         int64
	Name       string
	Currency   string
	ReportSlug string
	CreatedAt  int64
}

func (q *Queries) RestoreFund(ctx context.Context, arg RestoreFundParams) error {
	_, err := q.db.ExecContext(ctx, restoreFund,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.ReportSlug,
		arg.CreatedAt,
	)
	return err
}

const restoreIncidental = `-- name: RestoreIncidental :exec
INSERT INTO incidental (purpose_id, occasion, target_amount, opened_on, closed_on, minimum_per_member, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type RestoreIncidentalParams struct {
	PurposeID        int64
	Occasion         string
	TargetAmount     *int64
	OpenedOn         string
	ClosedOn         *string
	MinimumPerMember *int64
	CreatedAt        int64
}

func (q *Queries) RestoreIncidental(ctx context.Context, arg RestoreIncidentalParams) error {
	_, err := q.db.ExecContext(ctx, restoreIncidental,
		arg.PurposeID,
		arg.Occasion,
		arg.TargetAmount,
		arg.OpenedOn,
		arg.ClosedOn,
		arg.MinimumPerMember,
		arg.CreatedAt,
	)
	return err
}

const restoreIncidentalRecipient = `-- name: RestoreIncidentalRecipient :exec
INSERT INTO incidental_recipient (fund_id, purpose_id, member_id)
VALUES (?, ?, ?)
`

type RestoreIncidentalRecipientParams struct {
	FundID    int64
	PurposeID int64
	MemberID  int64
}

func (q *Queries) RestoreIncidentalRecipient(ctx context.Context, arg RestoreIncidentalRecipientParams) error {
	_, err := q.db.ExecContext(ctx, restoreIncidentalRecipient, arg.FundID, arg.PurposeID, arg.MemberID)
	return err
}

const restoreMember = `-- name: RestoreMember :exec
INSERT INTO member (id, fund_id, name, tier_id, joined_on, inactive_on, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type RestoreMemberParams struct {
	ID         int64
	FundID     int64
	Name       string
	TierID     *int64
	JoinedOn   *string
	InactiveOn *string
	CreatedAt  int64
}

func (q *Queries) RestoreMember(ctx context.Context, arg RestoreMemberParams) error {
	_, err := q.db.ExecContext(ctx, restoreMember,
		arg.ID,
		arg.FundID,
		arg.Name,
		arg.TierID,
		arg.JoinedOn,
		arg.InactiveOn,
		arg.CreatedAt,
	)
	return err
}

const restorePurpose = `-- name: RestorePurpose :exec
INSERT INTO purpose (id, fund_id, kind, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type RestorePurposeParams struct {
	ID        int64
	FundID    int64
	Kind      string
	Name      string
	CreatedAt int64
}

func (q *Queries) RestorePurpose(ctx context.Context, arg RestorePurposeParams) error {
	_, err := q.db.ExecContext(ctx, restorePurpose,
		arg.ID,
		arg.FundID,
		arg.Kind,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const restoreReceipt = `-- name: RestoreReceipt :exec
INSERT INTO receipt (id, fund_id, transaction_id, reimbursement_id, path, uploaded_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type RestoreReceiptParams struct {
	ID              int64
	FundID          int64
	TransactionID   *int64
	ReimbursementID *int64
	Path            string
	UploadedAt      int64
}

func (q *Queries) RestoreReceipt(ctx context.Context, arg RestoreReceiptParams) error {
	_, err := q.db.ExecContext(ctx, restoreReceipt,
		arg.ID,
		arg.FundID,
		arg.TransactionID,
		arg.ReimbursementID,
		arg.Path,
		arg.UploadedAt,
	)
	return err
}

const restoreReconciliation = `-- name: RestoreReconciliation :exec
INSERT INTO reconciliation (id, fund_id, performed_at, through_transaction_id, note, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type RestoreReconciliationParams struct {
	ID                   int64
	FundID               int64
	PerformedAt          int64
	ThroughTransactionID *int64
	Note                 *string
	CreatedAt            int64
}

func (q *Queries) RestoreReconciliation(ctx context.Context, arg RestoreReconciliationParams) error {
	_, err := q.db.ExecContext(ctx, restoreReconciliation,
		arg.ID,
		arg.FundID,
		arg.PerformedAt,
		arg.ThroughTransactionID,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const restoreReconciliationLine = `-- name: RestoreReconciliationLine :exec
INSERT INTO reconciliation_line (
  id, fund_id, reconciliation_id, account_id, recorded_amount, actual_amount,
  difference_amount, resolution, adjustment_transaction_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type RestoreReconciliationLineParams struct {
	ID                      int64
	FundID                  int64
	ReconciliationID        int64
	AccountID               int64
	RecordedAmount          int64
	ActualAmount            int64
	DifferenceAmount        int64
	Resolution              string
	AdjustmentTransactionID *int64
}

func (q *Queries) RestoreReconciliationLine(ctx context.Context, arg RestoreReconciliationLineParams) error {
	_, err := q.db.ExecContext(ctx, restoreReconciliationLine,
		arg.ID,
		arg.FundID,
		arg.ReconciliationID,
		arg.AccountID,
		arg.RecordedAmount,
		arg.ActualAmount,
		arg.DifferenceAmount,
		arg.Resolution,
		arg.AdjustmentTransactionID,
	)
	return err
}

const restoreReimbursement = `-- name: RestoreReimbursement :exec
INSERT INTO reimbursement (id, fund_id, member_id, purpose_id, amount, incurred_on, waived_on, note, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type RestoreReimbursementParams struct {
	ID         int64
	FundID     int64
	MemberID   int64
	PurposeID  int64
	Amount     int64
	IncurredOn string
	WaivedOn   *string
	Note       *string
	CreatedAt  int64
}

func (q *Queries) RestoreReimbursement(ctx context.Context, arg RestoreReimbursementParams) error {
	_, err := q.db.ExecContext(ctx, restoreReimbursement,
		arg.ID,
		arg.FundID,
		arg.MemberID,
		arg.PurposeID,
		arg.Amount,
		arg.IncurredOn,
		arg.WaivedOn,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const restoreTransaction = `-- name: RestoreTransaction :exec
INSERT INTO "transaction" (
  id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
  member_id, dues_period, reimbursement_id, transfer_id, reverses_transaction_id, note, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type RestoreTransactionParams struct {
	ID                    int64
	FundID                int64
	AccountID             int64
	PurposeID             int64
	Direction             string
	Amount                int64
	OccurredOn            string
	Kind                  string
	MemberID              *int64
	DuesPeriod            *string
	ReimbursementID       *int64
	TransferID            *int64
	ReversesTransactionID *int64
	Note                  *string
	CreatedAt             int64
}

// RestoreTransaction is the one insert restore.go must sequence with care
// (ADR-012's obligation 1): "transaction" keeps its transaction_named_row_shape
// BEFORE INSERT trigger live through a restore - on purpose, it is what
// refuses a hand-edited or corrupted backup - so every row naming a
// reverses_transaction_id must still be inserted after the row it names.
func (q *Queries) RestoreTransaction(ctx context.Context, arg RestoreTransactionParams) error {
	_, err := q.db.ExecContext(ctx, restoreTransaction,
		arg.ID,
		arg.FundID,
		arg.AccountID,
		arg.PurposeID,
		arg.Direction,
		arg.Amount,
		arg.OccurredOn,
		arg.Kind,
		arg.MemberID,
		arg.DuesPeriod,
		arg.ReimbursementID,
		arg.TransferID,
		arg.ReversesTransactionID,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const restoreTransfer = `-- name: RestoreTransfer :exec
INSERT INTO transfer (id, fund_id, kind, corrects_transaction_id, reason, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type RestoreTransferParams struct {
	ID                    int64
	FundID                int64
	Kind                  string
	CorrectsTransactionID *int64
	Reason                *string
	CreatedAt             int64
}

func (q *Queries) RestoreTransfer(ctx context.Context, arg RestoreTransferParams) error {
	_, err := q.db.ExecContext(ctx, restoreTransfer,
		arg.ID,
		arg.FundID,
		arg.Kind,
		arg.CorrectsTransactionID,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}
