// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package store

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (token, data, expires_at)
VALUES (?, ?, ?)
RETURNING token, data, expires_at
`

type CreateSessionParams struct {
	Token     string
	Data      []byte
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.Data, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.Token, &i.Data, &i.ExpiresAt)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session
WHERE expires_at <= ?
`

// DeleteExpiredSessions is the lazy sweep: called as a side effect of a
// session write, never by a background ticker (ADR-013's scope stays
// untouched by this slice).
func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token, data, expires_at
FROM session
WHERE token = ? AND expires_at > ?
`

type GetSessionParams struct {
	Token     string
	ExpiresAt int64
}

// GetSession only returns a row still inside its idle window; a session past
// expires_at is functionally gone even before DeleteExpiredSessions sweeps it.
func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.Token, &i.Data, &i.ExpiresAt)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE session
SET expires_at = ?1
WHERE token = ?2 AND expires_at > ?3
RETURNING token, data, expires_at
`

type TouchSessionParams struct {
	NewExpiresAt int64
	Token        string
	NotBefore    int64
}

// TouchSession is the sliding 30-day idle timeout (#113): every read that
// proves the session still valid pushes expires_at forward by the same fixed
// window, computed by the caller - there is no absolute cap to enforce here.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, touchSession, arg.NewExpiresAt, arg.Token, arg.NotBefore)
	var i Session
	err := row.Scan(&i.Token, &i.Data, &i.ExpiresAt)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO session (token, data, expires_at)
VALUES (?, ?, ?)
ON CONFLICT (token) DO UPDATE
SET data = excluded.data, expires_at = excluded.expires_at
RETURNING token, data, expires_at
`

type UpsertSessionParams struct {
	Token     string
	Data      []byte
	ExpiresAt int64
}

// UpsertSession is what a session store commits through: one atomic
// statement, because a commit rewrites a token that may or may not already
// exist. A delete-then-insert pair cannot stand in for it - ADR-004's
// SetMaxOpenConns(1) serialises the two statements but does not join them,
// so two concurrent requests carrying the same cookie interleave as
// DELETE / DELETE / INSERT / INSERT and the second INSERT trips
// session.token's primary key. ON CONFLICT makes the rewrite one statement,
// which is the only thing that closes that window.
func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, upsertSession, arg.Token, arg.Data, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.Token, &i.Data, &i.ExpiresAt)
	return i, err
}
