// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package store

import (
	"context"
)

const accountBalance = `-- name: AccountBalance :one
SELECT CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END), 0) AS INTEGER) AS balance_amount
FROM "transaction"
WHERE fund_id = ? AND account_id = ?
`

type AccountBalanceParams struct {
	FundID    int64
	AccountID int64
}

func (q *Queries) AccountBalance(ctx context.Context, arg AccountBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, accountBalance, arg.FundID, arg.AccountID)
	var balance_amount int64
	err := row.Scan(&balance_amount)
	return balance_amount, err
}

const accountBalanceThrough = `-- name: AccountBalanceThrough :one
SELECT CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END), 0) AS INTEGER) AS balance_amount
FROM "transaction"
WHERE fund_id = ? AND account_id = ? AND id <= ?
`

type AccountBalanceThroughParams struct {
	FundID    int64
	AccountID int64
	ID        int64
}

// The frozen half of a reconciliation: the same sum as AccountBalance, cut off
// at the snapshot's through_transaction_id. Ordered by id, not occurred_on, so
// a correction backdated after the count keeps its higher id and stays outside
// the old snapshot's arithmetic while counting toward today's balance.
func (q *Queries) AccountBalanceThrough(ctx context.Context, arg AccountBalanceThroughParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, accountBalanceThrough, arg.FundID, arg.AccountID, arg.ID)
	var balance_amount int64
	err := row.Scan(&balance_amount)
	return balance_amount, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO "transaction" (
  fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
  member_id, dues_period, reimbursement_id, transfer_id, reverses_transaction_id,
  note, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
          member_id, dues_period, reimbursement_id, transfer_id, reverses_transaction_id,
          note, created_at
`

type CreateTransactionParams struct {
	FundID                int64
	AccountID             int64
	PurposeID             int64
	Direction             string
	Amount                int64
	OccurredOn            string
	Kind                  string
	MemberID              *int64
	DuesPeriod            *string
	ReimbursementID       *int64
	TransferID            *int64
	ReversesTransactionID *int64
	Note                  *string
	CreatedAt             int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.FundID,
		arg.AccountID,
		arg.PurposeID,
		arg.Direction,
		arg.Amount,
		arg.OccurredOn,
		arg.Kind,
		arg.MemberID,
		arg.DuesPeriod,
		arg.ReimbursementID,
		arg.TransferID,
		arg.ReversesTransactionID,
		arg.Note,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.ReversesTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const duesPaidByMemberGroupedByPeriod = `-- name: DuesPaidByMemberGroupedByPeriod :many
SELECT CAST(dues_period AS TEXT) AS dues_period, CAST(COALESCE(SUM(amount), 0) AS INTEGER) AS paid_amount
FROM "transaction" t
WHERE t.fund_id = ? AND t.member_id = ? AND t.kind = 'dues'
  AND NOT EXISTS (SELECT 1 FROM "transaction" r WHERE r.reverses_transaction_id = t.id)
GROUP BY dues_period
`

type DuesPaidByMemberGroupedByPeriodParams struct {
	FundID   int64
	MemberID *int64
}

type DuesPaidByMemberGroupedByPeriodRow struct {
	DuesPeriod string
	PaidAmount int64
}

// DuesPaidByMemberGroupedByPeriod is DuesPaidByPeriod's transpose: every
// period one member has paid anything toward, in one pass over that
// member's whole history rather than one query per period
// (OutstandingDuesForMember's range walk). Same reversed-row exclusion
// (ADR-029) and the same CAST(... AS TEXT) forcing dues_period non-null
// LatestDuesPeriodPaidByMember already relies on - kind = 'dues' rows always
// carry a dues_period (schema CHECK), so this is never actually NULL, only
// untyped without the cast.
func (q *Queries) DuesPaidByMemberGroupedByPeriod(ctx context.Context, arg DuesPaidByMemberGroupedByPeriodParams) ([]DuesPaidByMemberGroupedByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, duesPaidByMemberGroupedByPeriod, arg.FundID, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuesPaidByMemberGroupedByPeriodRow{}
	for rows.Next() {
		var i DuesPaidByMemberGroupedByPeriodRow
		if err := rows.Scan(&i.DuesPeriod, &i.PaidAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const duesPaidByPeriod = `-- name: DuesPaidByPeriod :many
SELECT member_id, CAST(COALESCE(SUM(amount), 0) AS INTEGER) AS paid_amount
FROM "transaction" t
WHERE t.fund_id = ? AND t.kind = 'dues' AND t.dues_period = ?
  AND NOT EXISTS (SELECT 1 FROM "transaction" r WHERE r.reverses_transaction_id = t.id)
GROUP BY member_id
`

type DuesPaidByPeriodParams struct {
	FundID     int64
	DuesPeriod *string
}

type DuesPaidByPeriodRow struct {
	MemberID   *int64
	PaidAmount int64
}

// The roster query behind "who has paid / partially / not yet" for one
// dues_period, across every member in one pass rather than one query per
// member.
// The AND NOT EXISTS clause is ADR-029's half of the reversal design: a
// reversed dues row itself never matched kind = 'dues' in the first place
// (a reversal is posted as kind='adjustment'), so this drops the ORIGINAL
// row from the sum once something reverses it - which is what makes a
// reversed payment disappear from "paid" rather than simply counting twice.
func (q *Queries) DuesPaidByPeriod(ctx context.Context, arg DuesPaidByPeriodParams) ([]DuesPaidByPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, duesPaidByPeriod, arg.FundID, arg.DuesPeriod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuesPaidByPeriodRow{}
	for rows.Next() {
		var i DuesPaidByPeriodRow
		if err := rows.Scan(&i.MemberID, &i.PaidAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fundBalance = `-- name: FundBalance :one
SELECT CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END), 0) AS INTEGER) AS balance_amount
FROM "transaction"
WHERE fund_id = ?
`

// Every balance in Uruni is this shape: sum the ledger, never read a stored
// total (CLAUDE.md rule 2). direction carries the sign, so the CASE is the
// only place a minus appears. The CAST is not decoration - without it sqlc
// emits interface{} for the aggregate and the trust core loses its compiler
// exactly where it is needed most (ADR-024).
func (q *Queries) FundBalance(ctx context.Context, fundID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fundBalance, fundID)
	var balance_amount int64
	err := row.Scan(&balance_amount)
	return balance_amount, err
}

const getDuesPaymentReversal = `-- name: GetDuesPaymentReversal :one
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, reverses_transaction_id,
       note, created_at
FROM "transaction"
WHERE fund_id = ? AND reverses_transaction_id = ?
`

type GetDuesPaymentReversalParams struct {
	FundID                int64
	ReversesTransactionID *int64
}

// The reversed-once pre-check, same shape as GetReimbursementSettlement and
// GetOpeningBalance above: sql.ErrNoRows means "not yet reversed, proceed"
// (the expected, non-error path); a row means it already has been. The
// dues_payment_reversed_once partial unique index is the actual guarantee -
// this pre-check only turns a raw constraint violation into a clean, named
// error (ADR-029, mirroring ADR-027's ErrReimbursementAlreadySettled).
func (q *Queries) GetDuesPaymentReversal(ctx context.Context, arg GetDuesPaymentReversalParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getDuesPaymentReversal, arg.FundID, arg.ReversesTransactionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.ReversesTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getOpeningBalance = `-- name: GetOpeningBalance :one
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, note, created_at
FROM "transaction"
WHERE fund_id = ? AND account_id = ? AND kind = 'opening'
`

type GetOpeningBalanceParams struct {
	FundID    int64
	AccountID int64
}

type GetOpeningBalanceRow struct {
	ID              int64
	FundID          int64
	AccountID       int64
	PurposeID       int64
	Direction       string
	Amount          int64
	OccurredOn      string
	Kind            string
	MemberID        *int64
	DuesPeriod      *string
	ReimbursementID *int64
	TransferID      *int64
	Note            *string
	CreatedAt       int64
}

// The one-opening-per-account pre-check, same shape as
// GetReimbursementSettlement above: no aggregate, so a fund with no opening
// entry on this account yet returns a clean sql.ErrNoRows (the expected,
// non-error path) rather than a NULL forced through an aggregate. A row means
// one already exists.
func (q *Queries) GetOpeningBalance(ctx context.Context, arg GetOpeningBalanceParams) (GetOpeningBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, getOpeningBalance, arg.FundID, arg.AccountID)
	var i GetOpeningBalanceRow
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getReimbursementSettlement = `-- name: GetReimbursementSettlement :one
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, note, created_at
FROM "transaction"
WHERE fund_id = ? AND reimbursement_id = ? AND kind = 'reimbursement'
`

type GetReimbursementSettlementParams struct {
	FundID          int64
	ReimbursementID *int64
}

type GetReimbursementSettlementRow struct {
	ID              int64
	FundID          int64
	AccountID       int64
	PurposeID       int64
	Direction       string
	Amount          int64
	OccurredOn      string
	Kind            string
	MemberID        *int64
	DuesPeriod      *string
	ReimbursementID *int64
	TransferID      *int64
	Note            *string
	CreatedAt       int64
}

// The settle-once pre-check. Returns sql.ErrNoRows when the claim has not
// been settled yet (the expected, non-error path) or the settling row when
// it has.
func (q *Queries) GetReimbursementSettlement(ctx context.Context, arg GetReimbursementSettlementParams) (GetReimbursementSettlementRow, error) {
	row := q.db.QueryRowContext(ctx, getReimbursementSettlement, arg.FundID, arg.ReimbursementID)
	var i GetReimbursementSettlementRow
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, reverses_transaction_id,
       note, created_at
FROM "transaction"
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.ReversesTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionForFund = `-- name: GetTransactionForFund :one
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, reverses_transaction_id,
       note, created_at
FROM "transaction"
WHERE fund_id = ? AND id = ?
`

type GetTransactionForFundParams struct {
	FundID int64
	ID     int64
}

// The fund-scoped fetch a dues reversal fetches its target through (ADR-029):
// WHERE fund_id = ? AND id = ?, not id alone, so a transaction belonging to
// another fund reads as sql.ErrNoRows here rather than being found and only
// later rejected by the composite FK. GetTransaction above stays as it is -
// other callers already have their fund-scoped row in hand - this is the one
// new caller that fetches a transaction by id from an untrusted request.
func (q *Queries) GetTransactionForFund(ctx context.Context, arg GetTransactionForFundParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionForFund, arg.FundID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.ReversesTransactionID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const incidentalTotals = `-- name: IncidentalTotals :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE 0 END), 0) AS INTEGER) AS collected_amount,
  CAST(COALESCE(SUM(CASE WHEN direction = 'out' THEN amount ELSE 0 END), 0) AS INTEGER) AS disbursed_amount
FROM "transaction"
WHERE fund_id = ? AND purpose_id = ?
`

type IncidentalTotalsParams struct {
	FundID    int64
	PurposeID int64
}

type IncidentalTotalsRow struct {
	CollectedAmount int64
	DisbursedAmount int64
}

// The two figures PRD 7.5 wants shown side by side for an incidental envelope.
// Leftover is collected minus disbursed, computed in Go via money.Amount.Sub,
// rather than a third column here - one aggregate pass over the ledger is
// enough for both the display figures and the roll amount.
func (q *Queries) IncidentalTotals(ctx context.Context, arg IncidentalTotalsParams) (IncidentalTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, incidentalTotals, arg.FundID, arg.PurposeID)
	var i IncidentalTotalsRow
	err := row.Scan(&i.CollectedAmount, &i.DisbursedAmount)
	return i, err
}

const latestDuesPeriodPaidByMember = `-- name: LatestDuesPeriodPaidByMember :many
SELECT member_id, CAST(MAX(dues_period) AS TEXT) AS latest_period
FROM "transaction" t
WHERE t.fund_id = ? AND t.kind = 'dues'
  AND NOT EXISTS (SELECT 1 FROM "transaction" r WHERE r.reverses_transaction_id = t.id)
GROUP BY member_id
`

type LatestDuesPeriodPaidByMemberRow struct {
	MemberID     *int64
	LatestPeriod string
}

// The "paid in advance" signal. dues_period is 'YYYY-MM', so a lexicographic
// MAX is also the chronological one. The CAST(... AS TEXT) is load-bearing,
// not decoration: uncast, MAX(dues_period) generates interface{} - the same
// untyped-interface trap ADR-024 documents for SUM, reached here through MAX
// on a TEXT column - and a .(string) assertion on it is a live panic risk
// since drivers commonly hand back []byte.
// The AND NOT EXISTS clause is ADR-029's fix for the specific bug the chosen
// design exists to avoid: without it, a reversed row would still be the
// chronological MAX(dues_period) for its member, reading as "paid in
// advance" through a period that was reversed and is no longer paid at all.
func (q *Queries) LatestDuesPeriodPaidByMember(ctx context.Context, fundID int64) ([]LatestDuesPeriodPaidByMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, latestDuesPeriodPaidByMember, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestDuesPeriodPaidByMemberRow{}
	for rows.Next() {
		var i LatestDuesPeriodPaidByMemberRow
		if err := rows.Scan(&i.MemberID, &i.LatestPeriod); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuesPaymentsByMember = `-- name: ListDuesPaymentsByMember :many
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, note, created_at
FROM "transaction"
WHERE member_id = ? AND kind = 'dues'
ORDER BY dues_period, id
`

type ListDuesPaymentsByMemberRow struct {
	ID              int64
	FundID          int64
	AccountID       int64
	PurposeID       int64
	Direction       string
	Amount          int64
	OccurredOn      string
	Kind            string
	MemberID        *int64
	DuesPeriod      *string
	ReimbursementID *int64
	TransferID      *int64
	Note            *string
	CreatedAt       int64
}

func (q *Queries) ListDuesPaymentsByMember(ctx context.Context, memberID *int64) ([]ListDuesPaymentsByMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuesPaymentsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuesPaymentsByMemberRow{}
	for rows.Next() {
		var i ListDuesPaymentsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AccountID,
			&i.PurposeID,
			&i.Direction,
			&i.Amount,
			&i.OccurredOn,
			&i.Kind,
			&i.MemberID,
			&i.DuesPeriod,
			&i.ReimbursementID,
			&i.TransferID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByFund = `-- name: ListTransactionsByFund :many
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, reverses_transaction_id,
       note, created_at
FROM "transaction"
WHERE fund_id = ?
ORDER BY occurred_on, id
`

func (q *Queries) ListTransactionsByFund(ctx context.Context, fundID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AccountID,
			&i.PurposeID,
			&i.Direction,
			&i.Amount,
			&i.OccurredOn,
			&i.Kind,
			&i.MemberID,
			&i.DuesPeriod,
			&i.ReimbursementID,
			&i.TransferID,
			&i.ReversesTransactionID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTransactionIDByFund = `-- name: MaxTransactionIDByFund :one
SELECT id
FROM "transaction"
WHERE fund_id = ?
ORDER BY id DESC
LIMIT 1
`

// The reconciliation cutoff. Deliberately not an aggregate: SELECT
// CAST(MAX(id) AS INTEGER) generates a non-nullable (int64, error), and a
// bare aggregate with no GROUP BY still returns one row on an empty table
// with the value NULL - so a fund's first-ever reconciliation would fail
// with "converting NULL to int64 is unsupported". This form returns zero
// rows instead, giving a clean sql.ErrNoRows the domain reads as "no ledger
// yet".
func (q *Queries) MaxTransactionIDByFund(ctx context.Context, fundID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTransactionIDByFund, fundID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const purposeBalance = `-- name: PurposeBalance :one
SELECT CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END), 0) AS INTEGER) AS balance_amount
FROM "transaction"
WHERE fund_id = ? AND purpose_id = ?
`

type PurposeBalanceParams struct {
	FundID    int64
	PurposeID int64
}

func (q *Queries) PurposeBalance(ctx context.Context, arg PurposeBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, purposeBalance, arg.FundID, arg.PurposeID)
	var balance_amount int64
	err := row.Scan(&balance_amount)
	return balance_amount, err
}
