// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package store

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer (fund_id, kind, created_at)
VALUES (?, ?, ?)
RETURNING id, fund_id, kind, created_at
`

type CreateTransferParams struct {
	FundID    int64
	Kind      string
	CreatedAt int64
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer, arg.FundID, arg.Kind, arg.CreatedAt)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, fund_id, kind, created_at
FROM transfer
WHERE id = ?
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listTransfersByFund = `-- name: ListTransfersByFund :many
SELECT id, fund_id, kind, created_at
FROM transfer
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListTransfersByFund(ctx context.Context, fundID int64) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfersByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
