// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package store

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer (fund_id, kind, corrects_transaction_id, reason, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, fund_id, kind, corrects_transaction_id, reason, created_at
`

type CreateTransferParams struct {
	FundID                int64
	Kind                  string
	CorrectsTransactionID *int64
	Reason                *string
	CreatedAt             int64
}

// corrects_transaction_id is nil for every transfer but a purpose
// correction (ADR-033) - between_accounts and CloseIncidentalAndRoll's own
// reclass_purpose rolls both pass nil, the same NULL the schema's CHECK
// requires of anything that is not kind='reclass_purpose'. reason (ADR-036)
// is 'roll' for CloseIncidentalAndRoll, 'allocation' for a purpose move, and
// nil for every other pair - the same CHECK holds it to a reclass_purpose
// pair that corrects nothing.
func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.FundID,
		arg.Kind,
		arg.CorrectsTransactionID,
		arg.Reason,
		arg.CreatedAt,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.CorrectsTransactionID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const effectivePurposeForTransaction = `-- name: EffectivePurposeForTransaction :one
SELECT CAST(COALESCE((
  SELECT leg.purpose_id
  FROM transfer c
  JOIN "transaction" leg ON leg.transfer_id = c.id
  WHERE c.corrects_transaction_id = t.id
  GROUP BY leg.purpose_id
  HAVING SUM(CASE WHEN leg.direction = t.direction THEN 1 ELSE -1 END)
         + (leg.purpose_id = t.purpose_id) = 1
  LIMIT 1
), t.purpose_id) AS INTEGER) AS effective_purpose_id
FROM "transaction" t
WHERE t.fund_id = ? AND t.id = ?
`

type EffectivePurposeForTransactionParams struct {
	FundID int64
	ID     int64
}

// The effective peruntukan (ADR-033, #411): the tag this row's money is
// under now. Each correction moves the whole row from wherever it is to a new
// tag, so a row's corrections form a path starting at its stored purpose_id;
// the tag it ends on is the one the money entered once more than it left,
// counting the stored tag as the start. That needs no ordering of the
// corrections - transfer ids are not an order to rely on - and a row
// corrected and then corrected back ends where it began.
//
// Which leg of a correction is "entering" depends on the row's own direction:
// PostPurposeCorrection puts the target on the leg moving the same way as the
// row (an 'out' mis-tag needs the target on the 'out' leg, an 'in' on the
// 'in'), so leg.direction = t.direction reads back what it wrote. A row
// nothing corrects answers its own purpose_id.
func (q *Queries) EffectivePurposeForTransaction(ctx context.Context, arg EffectivePurposeForTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, effectivePurposeForTransaction, arg.FundID, arg.ID)
	var effective_purpose_id int64
	err := row.Scan(&effective_purpose_id)
	return effective_purpose_id, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, fund_id, kind, corrects_transaction_id, reason, created_at
FROM transfer
WHERE id = ?
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.CorrectsTransactionID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listTransfersByFund = `-- name: ListTransfersByFund :many
SELECT id, fund_id, kind, corrects_transaction_id, reason, created_at
FROM transfer
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListTransfersByFund(ctx context.Context, fundID int64) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfersByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Kind,
			&i.CorrectsTransactionID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
