// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package store

import (
	"context"
)

const accountBalance = `-- name: AccountBalance :one
SELECT CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END), 0) AS INTEGER) AS balance_amount
FROM "transaction"
WHERE fund_id = ? AND account_id = ?
`

type AccountBalanceParams struct {
	FundID    int64
	AccountID int64
}

func (q *Queries) AccountBalance(ctx context.Context, arg AccountBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, accountBalance, arg.FundID, arg.AccountID)
	var balance_amount int64
	err := row.Scan(&balance_amount)
	return balance_amount, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO "transaction" (
  fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
  member_id, dues_period, reimbursement_id, transfer_id, note, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
          member_id, dues_period, reimbursement_id, transfer_id, note, created_at
`

type CreateTransactionParams struct {
	FundID          int64
	AccountID       int64
	PurposeID       int64
	Direction       string
	Amount          int64
	OccurredOn      string
	Kind            string
	MemberID        *int64
	DuesPeriod      *string
	ReimbursementID *int64
	TransferID      *int64
	Note            *string
	CreatedAt       int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.FundID,
		arg.AccountID,
		arg.PurposeID,
		arg.Direction,
		arg.Amount,
		arg.OccurredOn,
		arg.Kind,
		arg.MemberID,
		arg.DuesPeriod,
		arg.ReimbursementID,
		arg.TransferID,
		arg.Note,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const fundBalance = `-- name: FundBalance :one
SELECT CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END), 0) AS INTEGER) AS balance_amount
FROM "transaction"
WHERE fund_id = ?
`

// Every balance in Uruni is this shape: sum the ledger, never read a stored
// total (CLAUDE.md rule 2). direction carries the sign, so the CASE is the
// only place a minus appears. The CAST is not decoration - without it sqlc
// emits interface{} for the aggregate and the trust core loses its compiler
// exactly where it is needed most (ADR-024).
func (q *Queries) FundBalance(ctx context.Context, fundID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, fundBalance, fundID)
	var balance_amount int64
	err := row.Scan(&balance_amount)
	return balance_amount, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, note, created_at
FROM "transaction"
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.AccountID,
		&i.PurposeID,
		&i.Direction,
		&i.Amount,
		&i.OccurredOn,
		&i.Kind,
		&i.MemberID,
		&i.DuesPeriod,
		&i.ReimbursementID,
		&i.TransferID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listDuesPaymentsByMember = `-- name: ListDuesPaymentsByMember :many
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, note, created_at
FROM "transaction"
WHERE member_id = ? AND kind = 'dues'
ORDER BY dues_period, id
`

func (q *Queries) ListDuesPaymentsByMember(ctx context.Context, memberID *int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listDuesPaymentsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AccountID,
			&i.PurposeID,
			&i.Direction,
			&i.Amount,
			&i.OccurredOn,
			&i.Kind,
			&i.MemberID,
			&i.DuesPeriod,
			&i.ReimbursementID,
			&i.TransferID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByFund = `-- name: ListTransactionsByFund :many
SELECT id, fund_id, account_id, purpose_id, direction, amount, occurred_on, kind,
       member_id, dues_period, reimbursement_id, transfer_id, note, created_at
FROM "transaction"
WHERE fund_id = ?
ORDER BY occurred_on, id
`

func (q *Queries) ListTransactionsByFund(ctx context.Context, fundID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.AccountID,
			&i.PurposeID,
			&i.Direction,
			&i.Amount,
			&i.OccurredOn,
			&i.Kind,
			&i.MemberID,
			&i.DuesPeriod,
			&i.ReimbursementID,
			&i.TransferID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purposeBalance = `-- name: PurposeBalance :one
SELECT CAST(COALESCE(SUM(CASE WHEN direction = 'in' THEN amount ELSE -amount END), 0) AS INTEGER) AS balance_amount
FROM "transaction"
WHERE fund_id = ? AND purpose_id = ?
`

type PurposeBalanceParams struct {
	FundID    int64
	PurposeID int64
}

func (q *Queries) PurposeBalance(ctx context.Context, arg PurposeBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, purposeBalance, arg.FundID, arg.PurposeID)
	var balance_amount int64
	err := row.Scan(&balance_amount)
	return balance_amount, err
}
