// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package store

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer (fund_id, kind, corrects_transaction_id, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, fund_id, kind, corrects_transaction_id, created_at
`

type CreateTransferParams struct {
	FundID                int64
	Kind                  string
	CorrectsTransactionID *int64
	CreatedAt             int64
}

// corrects_transaction_id is nil for every transfer but a purpose
// correction (ADR-033) - between_accounts and CloseIncidentalAndRoll's own
// reclass_purpose rolls both pass nil, the same NULL the schema's CHECK
// requires of anything that is not kind='reclass_purpose'.
func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.FundID,
		arg.Kind,
		arg.CorrectsTransactionID,
		arg.CreatedAt,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.CorrectsTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, fund_id, kind, corrects_transaction_id, created_at
FROM transfer
WHERE id = ?
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FundID,
		&i.Kind,
		&i.CorrectsTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const latestPurposeCorrectionForTransaction = `-- name: LatestPurposeCorrectionForTransaction :one
SELECT ol.purpose_id AS out_purpose_id, il.purpose_id AS in_purpose_id
FROM transfer tr
JOIN "transaction" ol ON ol.transfer_id = tr.id AND ol.direction = 'out'
JOIN "transaction" il ON il.transfer_id = tr.id AND il.direction = 'in'
WHERE tr.fund_id = ? AND tr.corrects_transaction_id = ?
ORDER BY tr.id DESC
LIMIT 1
`

type LatestPurposeCorrectionForTransactionParams struct {
	FundID                int64
	CorrectsTransactionID *int64
}

type LatestPurposeCorrectionForTransactionRow struct {
	OutPurposeID int64
	InPurposeID  int64
}

// The effective peruntukan lookup (ADR-033): the LATEST correction pointing
// at transaction_id, both its legs' purpose ids, or sql.ErrNoRows when none
// exists - the caller then falls back to the original row's own stored
// purpose_id. "Latest" is transfer.id DESC: a correction's two legs share
// one transfer row inserted once, so transfer.id already orders corrections
// the same way occurred_on cannot (ADR-033's own date-is-not-a-field rule
// means every correction of the same row can share a date).
//
// Both legs, not just one: which leg is "the new tag" depends on the
// ORIGINAL row's own direction, not on 'out' vs 'in' here - PostPurposeCorrection's
// own doc comment works out why an 'out' original needs the target at its
// 'out' leg while an 'in' original needs it at its 'in' leg. Deciding that
// in SQL would mean joining back to the original row a second time for a
// fact the caller already has in hand from its own first fetch; the caller
// (effectivePeruntukan) picks the correct one instead.
func (q *Queries) LatestPurposeCorrectionForTransaction(ctx context.Context, arg LatestPurposeCorrectionForTransactionParams) (LatestPurposeCorrectionForTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, latestPurposeCorrectionForTransaction, arg.FundID, arg.CorrectsTransactionID)
	var i LatestPurposeCorrectionForTransactionRow
	err := row.Scan(&i.OutPurposeID, &i.InPurposeID)
	return i, err
}

const listTransfersByFund = `-- name: ListTransfersByFund :many
SELECT id, fund_id, kind, corrects_transaction_id, created_at
FROM transfer
WHERE fund_id = ?
ORDER BY id
`

func (q *Queries) ListTransfersByFund(ctx context.Context, fundID int64) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfersByFund, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FundID,
			&i.Kind,
			&i.CorrectsTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
