/**
 * Stands in for `virtual:pwa-register/react` under vitest (aliased in
 * vite.config.ts's `test` block).
 *
 * The real module is generated by vite-plugin-pwa during a build, and jsdom
 * has no service worker to register anyway. The default here is the quiet
 * case - no update waiting - so every existing test that renders App keeps
 * seeing no banner; UpdateBanner.test.tsx overrides it with vi.mock to drive
 * the "update ready" state.
 */
export function useRegisterSW() {
  return {
    needRefresh: [false, () => {}] as [boolean, (v: boolean) => void],
    offlineReady: [false, () => {}] as [boolean, (v: boolean) => void],
    updateServiceWorker: async (_reloadPage?: boolean) => {},
  }
}
